// This file is auto-generated by @hey-api/openapi-ts

import type { DefaultError, UseMutationOptions } from '@tanstack/react-query';

import { type Options, postV1AuthLogin } from '../sdk.gen';
import type { PostV1AuthLoginData, PostV1AuthLoginResponse } from '../types.gen';

/**
 * Login
 */
export const postV1AuthLoginMutation = (options?: Partial<Options<PostV1AuthLoginData>>): UseMutationOptions<PostV1AuthLoginResponse, DefaultError, Options<PostV1AuthLoginData>> => {
    const mutationOptions: UseMutationOptions<PostV1AuthLoginResponse, DefaultError, Options<PostV1AuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postV1AuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
