// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: file_origin.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFileOriginIfAbsent = `-- name: CreateFileOriginIfAbsent :exec

insert into file_origin (
  file_id, origin, source_title,
  bin_source, bin_resolution, bin_modifier,
  release_group, edition, parsed,
  indexer_id, guid, download_job_id
) values (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10, $11, $12
)
on conflict (file_id) do nothing
`

type CreateFileOriginIfAbsentParams struct {
	FileID        pgtype.UUID `json:"file_id"`
	Origin        string      `json:"origin"`
	SourceTitle   *string     `json:"source_title"`
	BinSource     *string     `json:"bin_source"`
	BinResolution *string     `json:"bin_resolution"`
	BinModifier   *string     `json:"bin_modifier"`
	ReleaseGroup  *string     `json:"release_group"`
	Edition       *string     `json:"edition"`
	Parsed        []byte      `json:"parsed"`
	IndexerID     *int64      `json:"indexer_id"`
	Guid          *string     `json:"guid"`
	DownloadJobID pgtype.UUID `json:"download_job_id"`
}

// File Origin queries — the insert-once provenance sidecar of `file`.
// Stamps the origin the first time a file row is minted; later identity updates
// and re-scans never overwrite it (ON CONFLICT DO NOTHING is what protects the
// pre-rename source_title). :exec, not :one — a RETURNING on a no-op conflict
// yields zero rows, which apperrors.FromPg would misread as NotFound, and the
// write sites don't need the row back.
func (q *Queries) CreateFileOriginIfAbsent(ctx context.Context, arg CreateFileOriginIfAbsentParams) error {
	_, err := q.db.Exec(ctx, createFileOriginIfAbsent,
		arg.FileID,
		arg.Origin,
		arg.SourceTitle,
		arg.BinSource,
		arg.BinResolution,
		arg.BinModifier,
		arg.ReleaseGroup,
		arg.Edition,
		arg.Parsed,
		arg.IndexerID,
		arg.Guid,
		arg.DownloadJobID,
	)
	return err
}

const getFileOrigin = `-- name: GetFileOrigin :one
select file_id, origin, source_title, bin_source, bin_resolution, bin_modifier, release_group, edition, parsed, indexer_id, guid, download_job_id, captured_at from file_origin where file_id = $1
`

func (q *Queries) GetFileOrigin(ctx context.Context, fileID pgtype.UUID) (FileOrigin, error) {
	row := q.db.QueryRow(ctx, getFileOrigin, fileID)
	var i FileOrigin
	err := row.Scan(
		&i.FileID,
		&i.Origin,
		&i.SourceTitle,
		&i.BinSource,
		&i.BinResolution,
		&i.BinModifier,
		&i.ReleaseGroup,
		&i.Edition,
		&i.Parsed,
		&i.IndexerID,
		&i.Guid,
		&i.DownloadJobID,
		&i.CapturedAt,
	)
	return i, err
}
