// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: import_task_events.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createImportTaskEvent = `-- name: CreateImportTaskEvent :one

INSERT INTO import_task_event (
  import_task_id,
  event_type,
  old_status,
  new_status,
  message,
  metadata
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, import_task_id, event_type, old_status, new_status, message, metadata, created_at
`

type CreateImportTaskEventParams struct {
	ImportTaskID pgtype.UUID `json:"import_task_id"`
	EventType    string      `json:"event_type"`
	OldStatus    *string     `json:"old_status"`
	NewStatus    *string     `json:"new_status"`
	Message      *string     `json:"message"`
	Metadata     []byte      `json:"metadata"`
}

// Import task events (audit log)
func (q *Queries) CreateImportTaskEvent(ctx context.Context, arg CreateImportTaskEventParams) (ImportTaskEvent, error) {
	row := q.db.QueryRow(ctx, createImportTaskEvent,
		arg.ImportTaskID,
		arg.EventType,
		arg.OldStatus,
		arg.NewStatus,
		arg.Message,
		arg.Metadata,
	)
	var i ImportTaskEvent
	err := row.Scan(
		&i.ID,
		&i.ImportTaskID,
		&i.EventType,
		&i.OldStatus,
		&i.NewStatus,
		&i.Message,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getImportTaskTimeline = `-- name: GetImportTaskTimeline :many
SELECT
  id,
  import_task_id,
  event_type,
  old_status,
  new_status,
  message,
  metadata,
  created_at
FROM import_task_event
WHERE import_task_id = $1
ORDER BY created_at ASC
`

// Get events for a specific import task
func (q *Queries) GetImportTaskTimeline(ctx context.Context, importTaskID pgtype.UUID) ([]ImportTaskEvent, error) {
	rows, err := q.db.Query(ctx, getImportTaskTimeline, importTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportTaskEvent
	for rows.Next() {
		var i ImportTaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.ImportTaskID,
			&i.EventType,
			&i.OldStatus,
			&i.NewStatus,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportTaskEvents = `-- name: ListImportTaskEvents :many
SELECT id, import_task_id, event_type, old_status, new_status, message, metadata, created_at FROM import_task_event
WHERE import_task_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListImportTaskEvents(ctx context.Context, importTaskID pgtype.UUID) ([]ImportTaskEvent, error) {
	rows, err := q.db.Query(ctx, listImportTaskEvents, importTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportTaskEvent
	for rows.Next() {
		var i ImportTaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.ImportTaskID,
			&i.EventType,
			&i.OldStatus,
			&i.NewStatus,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentImportTaskEvents = `-- name: ListRecentImportTaskEvents :many
SELECT id, import_task_id, event_type, old_status, new_status, message, metadata, created_at FROM import_task_event
ORDER BY created_at DESC
LIMIT $2
OFFSET $1
`

type ListRecentImportTaskEventsParams struct {
	OffsetVal int32 `json:"offset_val"`
	LimitVal  int32 `json:"limit_val"`
}

func (q *Queries) ListRecentImportTaskEvents(ctx context.Context, arg ListRecentImportTaskEventsParams) ([]ImportTaskEvent, error) {
	rows, err := q.db.Query(ctx, listRecentImportTaskEvents, arg.OffsetVal, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportTaskEvent
	for rows.Next() {
		var i ImportTaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.ImportTaskID,
			&i.EventType,
			&i.OldStatus,
			&i.NewStatus,
			&i.Message,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
