// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimInvite = `-- name: ClaimInvite :exec
UPDATE user_invite
SET claimed_at = now()
WHERE id = $1 AND claimed_at IS NULL
`

func (q *Queries) ClaimInvite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, claimInvite, id)
	return err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO user_invite (email, invited_by)
VALUES ($1, $2)
RETURNING id, email, invited_by, created_at, claimed_at
`

type CreateInviteParams struct {
	Email     string      `json:"email"`
	InvitedBy pgtype.UUID `json:"invited_by"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (UserInvite, error) {
	row := q.db.QueryRow(ctx, createInvite, arg.Email, arg.InvitedBy)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ClaimedAt,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM user_invite WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvite, id)
	return err
}

const getInviteByEmail = `-- name: GetInviteByEmail :one
SELECT id, email, invited_by, created_at, claimed_at FROM user_invite
WHERE lower(email) = lower($1) AND claimed_at IS NULL
`

func (q *Queries) GetInviteByEmail(ctx context.Context, lower string) (UserInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByEmail, lower)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.ClaimedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT id, email, invited_by, created_at, claimed_at FROM user_invite
ORDER BY created_at DESC
`

func (q *Queries) ListInvites(ctx context.Context) ([]UserInvite, error) {
	rows, err := q.db.Query(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserInvite
	for rows.Next() {
		var i UserInvite
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
