// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: libraries.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLibrary = `-- name: CreateLibrary :one
insert into library (name, type, root_path, enabled)
values ($1, $2, $3, $4)
returning id, name, type, root_path, enabled, created_at, updated_at
`

type CreateLibraryParams struct {
	Name     string `json:"name"`
	Type     string `json:"type"`
	RootPath string `json:"root_path"`
	Enabled  bool   `json:"enabled"`
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, createLibrary,
		arg.Name,
		arg.Type,
		arg.RootPath,
		arg.Enabled,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.RootPath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLibrary = `-- name: DeleteLibrary :exec
delete from library where id = $1
`

func (q *Queries) DeleteLibrary(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLibrary, id)
	return err
}

const getLibrary = `-- name: GetLibrary :one
select id, name, type, root_path, enabled, created_at, updated_at from library
where id = $1
`

func (q *Queries) GetLibrary(ctx context.Context, id pgtype.UUID) (Library, error) {
	row := q.db.QueryRow(ctx, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.RootPath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLibraries = `-- name: ListLibraries :many
select id, name, type, root_path, enabled, created_at, updated_at from library
order by name asc
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.Query(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.RootPath,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLibrary = `-- name: UpdateLibrary :one
update library
set name = $2,
    type = $3,
    root_path = $4,
    enabled = $5,
    updated_at = now()
where id = $1
returning id, name, type, root_path, enabled, created_at, updated_at
`

type UpdateLibraryParams struct {
	ID       pgtype.UUID `json:"id"`
	Name     string      `json:"name"`
	Type     string      `json:"type"`
	RootPath string      `json:"root_path"`
	Enabled  bool        `json:"enabled"`
}

func (q *Queries) UpdateLibrary(ctx context.Context, arg UpdateLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, updateLibrary,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.RootPath,
		arg.Enabled,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.RootPath,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
