// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: push.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVAPIDConfig = `-- name: CreateVAPIDConfig :one
insert into vapid_config (public_key, private_key, subject)
values ($1, $2, $3)
returning id, public_key, private_key, subject, created_at, updated_at
`

type CreateVAPIDConfigParams struct {
	PublicKey  string `json:"public_key"`
	PrivateKey string `json:"private_key"`
	Subject    string `json:"subject"`
}

func (q *Queries) CreateVAPIDConfig(ctx context.Context, arg CreateVAPIDConfigParams) (VapidConfig, error) {
	row := q.db.QueryRow(ctx, createVAPIDConfig, arg.PublicKey, arg.PrivateKey, arg.Subject)
	var i VapidConfig
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.Subject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :execrows
delete from push_subscription
where endpoint = $1
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePushSubscriptionForUser = `-- name: DeletePushSubscriptionForUser :execrows
delete from push_subscription
where endpoint = $1 and user_id = $2
`

type DeletePushSubscriptionForUserParams struct {
	Endpoint string      `json:"endpoint"`
	UserID   pgtype.UUID `json:"user_id"`
}

// DeletePushSubscriptionForUser scopes deletion to the owner so one user cannot
// unsubscribe another's device by guessing an endpoint.
func (q *Queries) DeletePushSubscriptionForUser(ctx context.Context, arg DeletePushSubscriptionForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscriptionForUser, arg.Endpoint, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVAPIDConfig = `-- name: GetVAPIDConfig :one

select id, public_key, private_key, subject, created_at, updated_at from vapid_config
limit 1
`

// Web Push: VAPID identity (singleton) and per-browser subscriptions.
func (q *Queries) GetVAPIDConfig(ctx context.Context) (VapidConfig, error) {
	row := q.db.QueryRow(ctx, getVAPIDConfig)
	var i VapidConfig
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.Subject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPushSubscriptionsByUser = `-- name: ListPushSubscriptionsByUser :many
select id, user_id, endpoint, p256dh, auth, user_agent, created_at, last_used_at from push_subscription
where user_id = $1
order by created_at
`

func (q *Queries) ListPushSubscriptionsByUser(ctx context.Context, userID pgtype.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchPushSubscription = `-- name: TouchPushSubscription :exec
update push_subscription
set last_used_at = now()
where endpoint = $1
`

func (q *Queries) TouchPushSubscription(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, touchPushSubscription, endpoint)
	return err
}

const updateVAPIDSubject = `-- name: UpdateVAPIDSubject :one
update vapid_config
set subject = $1,
    updated_at = now()
where id = $2
returning id, public_key, private_key, subject, created_at, updated_at
`

type UpdateVAPIDSubjectParams struct {
	Subject string      `json:"subject"`
	ID      pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateVAPIDSubject(ctx context.Context, arg UpdateVAPIDSubjectParams) (VapidConfig, error) {
	row := q.db.QueryRow(ctx, updateVAPIDSubject, arg.Subject, arg.ID)
	var i VapidConfig
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.Subject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one
insert into push_subscription (user_id, endpoint, p256dh, auth, user_agent)
values ($1, $2, $3, $4, $5)
on conflict (endpoint) do update
set user_id = excluded.user_id,
    p256dh = excluded.p256dh,
    auth = excluded.auth,
    user_agent = excluded.user_agent,
    last_used_at = now()
returning id, user_id, endpoint, p256dh, auth, user_agent, created_at, last_used_at
`

type UpsertPushSubscriptionParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Endpoint  string      `json:"endpoint"`
	P256dh    string      `json:"p256dh"`
	Auth      string      `json:"auth"`
	UserAgent *string     `json:"user_agent"`
}

// UpsertPushSubscription registers (or refreshes) a browser's subscription.
// endpoint is the natural key: a re-subscribe from the same browser re-uses the
// endpoint, so we refresh its keys/owner/user_agent and bump last_used_at rather
// than inserting a duplicate. This also re-homes an endpoint if a different user
// signs in on the same browser.
func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserAgent,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}
