// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: want.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimRunnableWants = `-- name: ClaimRunnableWants :many
WITH cte AS (
  SELECT id
  FROM want
  WHERE status = 'pending'
    AND next_run_at <= now()
  ORDER BY next_run_at ASC
  FOR UPDATE SKIP LOCKED
  LIMIT $1
)
UPDATE want w
SET status = 'searching',
    updated_at = now()
FROM cte
WHERE w.id = cte.id
RETURNING w.id, w.tracking_id, w.media_item_id, w.quality_profile_id, w.status, w.next_run_at, w.attempt_count, w.last_error, w.created_at, w.updated_at
`

// ClaimRunnableWants atomically claims pending wants that are due, flipping them
// to 'searching' so a concurrent claim skips them. FOR UPDATE SKIP LOCKED is the
// work-dispatch pattern shared with ClaimRunnableDownloadJobs/ImportTasks.
func (q *Queries) ClaimRunnableWants(ctx context.Context, limit int32) ([]Want, error) {
	rows, err := q.db.Query(ctx, claimRunnableWants, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Want
	for rows.Next() {
		var i Want
		if err := rows.Scan(
			&i.ID,
			&i.TrackingID,
			&i.MediaItemID,
			&i.QualityProfileID,
			&i.Status,
			&i.NextRunAt,
			&i.AttemptCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWant = `-- name: CreateWant :one

INSERT INTO want (tracking_id, media_item_id, quality_profile_id, status)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at
`

type CreateWantParams struct {
	TrackingID       pgtype.UUID `json:"tracking_id"`
	MediaItemID      pgtype.UUID `json:"media_item_id"`
	QualityProfileID pgtype.UUID `json:"quality_profile_id"`
	Status           string      `json:"status"`
}

// Wants: the work item, shaped as a durable work-dispatch queue.
func (q *Queries) CreateWant(ctx context.Context, arg CreateWantParams) (Want, error) {
	row := q.db.QueryRow(ctx, createWant,
		arg.TrackingID,
		arg.MediaItemID,
		arg.QualityProfileID,
		arg.Status,
	)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWant = `-- name: GetWant :one
SELECT id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at FROM want
WHERE id = $1
`

func (q *Queries) GetWant(ctx context.Context, id pgtype.UUID) (Want, error) {
	row := q.db.QueryRow(ctx, getWant, id)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWantsByTracking = `-- name: ListWantsByTracking :many
SELECT id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at FROM want
WHERE tracking_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWantsByTracking(ctx context.Context, trackingID pgtype.UUID) ([]Want, error) {
	rows, err := q.db.Query(ctx, listWantsByTracking, trackingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Want
	for rows.Next() {
		var i Want
		if err := rows.Scan(
			&i.ID,
			&i.TrackingID,
			&i.MediaItemID,
			&i.QualityProfileID,
			&i.Status,
			&i.NextRunAt,
			&i.AttemptCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWantStatus = `-- name: SetWantStatus :one
UPDATE want
SET status = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at
`

type SetWantStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SetWantStatus(ctx context.Context, arg SetWantStatusParams) (Want, error) {
	row := q.db.QueryRow(ctx, setWantStatus, arg.Status, arg.ID)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
