// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: want.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelWant = `-- name: CancelWant :one
UPDATE want
SET status = 'canceled',
    updated_at = now()
WHERE id = $1
  AND status NOT IN ('available', 'failed', 'canceled')
RETURNING id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at
`

// CancelWant terminally cancels a want via compare-and-swap: it succeeds only
// while the want is non-terminal, so a want already 'available'/'failed'/
// 'canceled' matches 0 rows (surfaced as pgx.ErrNoRows). The service reads that
// as "nothing to cancel" — idempotent on an already-canceled want, a conflict
// otherwise.
func (q *Queries) CancelWant(ctx context.Context, id pgtype.UUID) (Want, error) {
	row := q.db.QueryRow(ctx, cancelWant, id)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimRunnableWants = `-- name: ClaimRunnableWants :many
WITH cte AS (
  SELECT id
  FROM want
  WHERE status = 'pending'
    AND next_run_at <= now()
  ORDER BY next_run_at ASC
  FOR UPDATE SKIP LOCKED
  LIMIT $1
)
UPDATE want w
SET status = 'searching',
    updated_at = now()
FROM cte
WHERE w.id = cte.id
RETURNING w.id, w.tracking_id, w.media_item_id, w.quality_profile_id, w.status, w.next_run_at, w.attempt_count, w.last_error, w.created_at, w.updated_at
`

// ClaimRunnableWants atomically claims pending wants that are due, flipping them
// to 'searching' so a concurrent claim skips them. FOR UPDATE SKIP LOCKED is the
// work-dispatch pattern shared with ClaimRunnableDownloadJobs/ImportTasks.
func (q *Queries) ClaimRunnableWants(ctx context.Context, limit int32) ([]Want, error) {
	rows, err := q.db.Query(ctx, claimRunnableWants, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Want
	for rows.Next() {
		var i Want
		if err := rows.Scan(
			&i.ID,
			&i.TrackingID,
			&i.MediaItemID,
			&i.QualityProfileID,
			&i.Status,
			&i.NextRunAt,
			&i.AttemptCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWant = `-- name: CreateWant :one

INSERT INTO want (tracking_id, media_item_id, quality_profile_id, status)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at
`

type CreateWantParams struct {
	TrackingID       pgtype.UUID `json:"tracking_id"`
	MediaItemID      pgtype.UUID `json:"media_item_id"`
	QualityProfileID pgtype.UUID `json:"quality_profile_id"`
	Status           string      `json:"status"`
}

// Wants: the work item, shaped as a durable work-dispatch queue.
func (q *Queries) CreateWant(ctx context.Context, arg CreateWantParams) (Want, error) {
	row := q.db.QueryRow(ctx, createWant,
		arg.TrackingID,
		arg.MediaItemID,
		arg.QualityProfileID,
		arg.Status,
	)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWant = `-- name: GetWant :one
SELECT id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at FROM want
WHERE id = $1
`

func (q *Queries) GetWant(ctx context.Context, id pgtype.UUID) (Want, error) {
	row := q.db.QueryRow(ctx, getWant, id)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grabWant = `-- name: GrabWant :one
UPDATE want
SET status = 'grabbed',
    updated_at = now()
WHERE id = $1
  AND status = 'searching'
RETURNING id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at
`

// GrabWant claims a searching want for grab via compare-and-swap: it succeeds
// only while the want is still 'searching', and the UPDATE holds the row lock
// through commit so concurrent grabbers serialize and the loser matches 0 rows.
// This is the dedup guard against the reaper re-claiming a want a live worker
// still holds. A 0-row match surfaces as pgx.ErrNoRows; the repo reads it as
// "no longer owned".
func (q *Queries) GrabWant(ctx context.Context, id pgtype.UUID) (Want, error) {
	row := q.db.QueryRow(ctx, grabWant, id)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grabWantManual = `-- name: GrabWantManual :one
UPDATE want
SET status = 'grabbed',
    updated_at = now()
WHERE id = $1
  AND status IN ('pending', 'searching', 'failed', 'canceled')
RETURNING id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at
`

// GrabWantManual flips a want to 'grabbed' for the manual-grab path via
// compare-and-swap. The IN (...) set is the race-safe gate: it fires only from
// the pre-grab/terminal states a manual grab may pre-empt or reactivate
// ('pending'/'searching' pre-empts the autonomous search; 'failed'/'canceled'
// reactivates). A want the worker already advanced ('grabbed'/'downloading'/
// 'imported'/'available') isn't in the set, so the manual grab loses cleanly
// (0 rows, surfaced as pgx.ErrNoRows) and the service rejects it as a conflict.
func (q *Queries) GrabWantManual(ctx context.Context, id pgtype.UUID) (Want, error) {
	row := q.db.QueryRow(ctx, grabWantManual, id)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWantsByTracking = `-- name: ListWantsByTracking :many
SELECT id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at FROM want
WHERE tracking_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWantsByTracking(ctx context.Context, trackingID pgtype.UUID) ([]Want, error) {
	rows, err := q.db.Query(ctx, listWantsByTracking, trackingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Want
	for rows.Next() {
		var i Want
		if err := rows.Scan(
			&i.ID,
			&i.TrackingID,
			&i.MediaItemID,
			&i.QualityProfileID,
			&i.Status,
			&i.NextRunAt,
			&i.AttemptCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWantFailed = `-- name: MarkWantFailed :one
UPDATE want
SET status = 'failed',
    last_error = $1,
    updated_at = now()
WHERE id = $2
  AND status = 'searching'
RETURNING id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at
`

type MarkWantFailedParams struct {
	LastError *string     `json:"last_error"`
	ID        pgtype.UUID `json:"id"`
}

// MarkWantFailed terminally fails a want. Mirrors MarkDownloadJobFailed. The
// 'searching' guard keeps the worker from clobbering a want the reaper reset and
// another worker re-grabbed.
func (q *Queries) MarkWantFailed(ctx context.Context, arg MarkWantFailedParams) (Want, error) {
	row := q.db.QueryRow(ctx, markWantFailed, arg.LastError, arg.ID)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const mirrorWantStatus = `-- name: MirrorWantStatus :one
UPDATE want
SET status = $1,
    updated_at = now()
WHERE id = $2
  AND status NOT IN ('available', 'failed', 'canceled')
RETURNING id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at
`

type MirrorWantStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

// MirrorWantStatus is the terminal-sticky want-status mirror the workers route
// through: it sets status only while the want is non-terminal, so a want flipped
// 'canceled' (or already 'available'/'failed') can't be resurrected by a late
// in-flight job/task completing after a cancel. A 0-row match (pgx.ErrNoRows)
// means the guard blocked the mirror. Every legitimate forward mirror has a
// non-terminal source state, so the guard only ever blocks resurrection.
func (q *Queries) MirrorWantStatus(ctx context.Context, arg MirrorWantStatusParams) (Want, error) {
	row := q.db.QueryRow(ctx, mirrorWantStatus, arg.Status, arg.ID)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const rearmWant = `-- name: RearmWant :one
UPDATE want
SET status = 'pending',
    attempt_count = 0,
    last_error = NULL,
    next_run_at = now(),
    updated_at = now()
WHERE id = $1
  AND status IN ('failed', 'canceled')
RETURNING id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at
`

// RearmWant resumes a terminal want when its movie is re-requested, flipping a
// 'failed'/'canceled' want back to 'pending' with the backoff reset so the
// AcquisitionWorker re-claims it. The single-atom invariant means a re-request
// re-arms the one existing want rather than creating a second. A 0-row match
// (pgx.ErrNoRows) means the want is in-flight or already 'available' — nothing
// to resume. Mirrors GrabWant's CAS contract.
func (q *Queries) RearmWant(ctx context.Context, id pgtype.UUID) (Want, error) {
	row := q.db.QueryRow(ctx, rearmWant, id)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reclaimStaleSearchingWants = `-- name: ReclaimStaleSearchingWants :many
UPDATE want
SET status = 'pending',
    last_error = $1,
    next_run_at = now(),
    updated_at = now()
WHERE status = 'searching'
  AND updated_at < $2
RETURNING id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at
`

type ReclaimStaleSearchingWantsParams struct {
	LastError   *string   `json:"last_error"`
	StaleBefore time.Time `json:"stale_before"`
}

// ReclaimStaleSearchingWants resets wants wedged in 'searching' past the cutoff
// back to 'pending' so the AcquisitionWorker reclaims them — the self-heal for a
// crash between ClaimRunnableWants' flip and a terminal transition. Reset-only:
// attempt_count is untouched and no want is failed (mirrors the "no release yet"
// reschedule). The cutoff is passed from Go for testability.
func (q *Queries) ReclaimStaleSearchingWants(ctx context.Context, arg ReclaimStaleSearchingWantsParams) ([]Want, error) {
	rows, err := q.db.Query(ctx, reclaimStaleSearchingWants, arg.LastError, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Want
	for rows.Next() {
		var i Want
		if err := rows.Scan(
			&i.ID,
			&i.TrackingID,
			&i.MediaItemID,
			&i.QualityProfileID,
			&i.Status,
			&i.NextRunAt,
			&i.AttemptCount,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleWantRetry = `-- name: ScheduleWantRetry :one
UPDATE want
SET status = 'pending',
    attempt_count = attempt_count + 1,
    last_error = $1,
    next_run_at = $2,
    updated_at = now()
WHERE id = $3
  AND status = 'searching'
RETURNING id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at
`

type ScheduleWantRetryParams struct {
	LastError *string     `json:"last_error"`
	NextRunAt time.Time   `json:"next_run_at"`
	ID        pgtype.UUID `json:"id"`
}

// ScheduleWantRetry returns a want to 'pending' with a backoff so the
// AcquisitionWorker can reclaim it; want has no error_kind column, only
// last_error. Mirrors ScheduleDownloadJobRetry. The 'searching' guard keeps the
// worker from reverting a want the reaper reset and another worker re-grabbed.
func (q *Queries) ScheduleWantRetry(ctx context.Context, arg ScheduleWantRetryParams) (Want, error) {
	row := q.db.QueryRow(ctx, scheduleWantRetry, arg.LastError, arg.NextRunAt, arg.ID)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setWantStatus = `-- name: SetWantStatus :one
UPDATE want
SET status = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, tracking_id, media_item_id, quality_profile_id, status, next_run_at, attempt_count, last_error, created_at, updated_at
`

type SetWantStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SetWantStatus(ctx context.Context, arg SetWantStatusParams) (Want, error) {
	row := q.db.QueryRow(ctx, setWantStatus, arg.Status, arg.ID)
	var i Want
	err := row.Scan(
		&i.ID,
		&i.TrackingID,
		&i.MediaItemID,
		&i.QualityProfileID,
		&i.Status,
		&i.NextRunAt,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
