FROM node:20 AS web-build
WORKDIR /web
COPY web/package*.json ./
RUN npm ci
COPY web/ .
RUN npm run build

FROM nginx:alpine
COPY --from=web-build /web/dist /usr/share/nginx/html
COPY ops-old/nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
