#!/command/with-contenv bash
set -euo pipefail

mode="${APP_ENV:-prod}"

if [[ "$mode" == "dev" ]]; then
  echo "[backend] dev mode: go run ./cmd/backend"
  cd /app/backend
  exec air
else
  echo "[backend] prod mode: /opt/app/backend"
  exec /opt/app/backend
fi
