// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteV1LibrariesByIdData, DeleteV1LibrariesByIdResponses, GetHealthData, GetHealthResponses, GetV1HomeData, GetV1HomeResponses, GetV1LibrariesByIdData, GetV1LibrariesByIdResponses, GetV1LibrariesData, GetV1LibrariesResponses, GetV1LibraryData, GetV1LibraryResponses, GetV1MovieByIdData, GetV1MovieByIdResponses, GetV1SeriesByIdData, GetV1SeriesByIdResponses, GetV1SettingsData, GetV1SettingsResponses, PatchV1SettingsData, PatchV1SettingsErrors, PatchV1SettingsResponses, PostV1AuthLoginData, PostV1AuthLoginResponses, PostV1LibrariesByIdScanData, PostV1LibrariesByIdScanResponses, PostV1LibrariesData, PostV1LibrariesErrors, PostV1LibrariesResponses, PutV1LibrariesByIdData, PutV1LibrariesByIdErrors, PutV1LibrariesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Health check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options
    });
};

/**
 * Login
 */
export const postV1AuthLogin = <ThrowOnError extends boolean = false>(options: Options<PostV1AuthLoginData, ThrowOnError>) => {
    return (options.client ?? client).post<PostV1AuthLoginResponses, unknown, ThrowOnError>({
        url: '/v1/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get rails
 */
export const getV1Home = <ThrowOnError extends boolean = false>(options?: Options<GetV1HomeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetV1HomeResponses, unknown, ThrowOnError>({
        url: '/v1/home',
        ...options
    });
};

/**
 * List libraries
 */
export const getV1Libraries = <ThrowOnError extends boolean = false>(options?: Options<GetV1LibrariesData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetV1LibrariesResponses, unknown, ThrowOnError>({
        url: '/v1/libraries',
        ...options
    });
};

/**
 * Create library
 */
export const postV1Libraries = <ThrowOnError extends boolean = false>(options: Options<PostV1LibrariesData, ThrowOnError>) => {
    return (options.client ?? client).post<PostV1LibrariesResponses, PostV1LibrariesErrors, ThrowOnError>({
        url: '/v1/libraries',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete library
 */
export const deleteV1LibrariesById = <ThrowOnError extends boolean = false>(options: Options<DeleteV1LibrariesByIdData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteV1LibrariesByIdResponses, unknown, ThrowOnError>({
        url: '/v1/libraries/{id}',
        ...options
    });
};

/**
 * Get library
 */
export const getV1LibrariesById = <ThrowOnError extends boolean = false>(options?: Options<GetV1LibrariesByIdData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetV1LibrariesByIdResponses, unknown, ThrowOnError>({
        url: '/v1/libraries/{id}',
        ...options
    });
};

/**
 * Update library
 */
export const putV1LibrariesById = <ThrowOnError extends boolean = false>(options: Options<PutV1LibrariesByIdData, ThrowOnError>) => {
    return (options.client ?? client).put<PutV1LibrariesByIdResponses, PutV1LibrariesByIdErrors, ThrowOnError>({
        url: '/v1/libraries/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Scan library
 */
export const postV1LibrariesByIdScan = <ThrowOnError extends boolean = false>(options: Options<PostV1LibrariesByIdScanData, ThrowOnError>) => {
    return (options.client ?? client).post<PostV1LibrariesByIdScanResponses, unknown, ThrowOnError>({
        url: '/v1/libraries/{id}/scan',
        ...options
    });
};

/**
 * List media items
 */
export const getV1Library = <ThrowOnError extends boolean = false>(options?: Options<GetV1LibraryData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetV1LibraryResponses, unknown, ThrowOnError>({
        url: '/v1/library',
        ...options
    });
};

/**
 * Get movie
 */
export const getV1MovieById = <ThrowOnError extends boolean = false>(options: Options<GetV1MovieByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetV1MovieByIdResponses, unknown, ThrowOnError>({
        url: '/v1/movie/{id}',
        ...options
    });
};

/**
 * Get series
 */
export const getV1SeriesById = <ThrowOnError extends boolean = false>(options: Options<GetV1SeriesByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<GetV1SeriesByIdResponses, unknown, ThrowOnError>({
        url: '/v1/series/{id}',
        ...options
    });
};

/**
 * List settings
 */
export const getV1Settings = <ThrowOnError extends boolean = false>(options?: Options<GetV1SettingsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetV1SettingsResponses, unknown, ThrowOnError>({
        url: '/v1/settings',
        ...options
    });
};

/**
 * Update a setting
 */
export const patchV1Settings = <ThrowOnError extends boolean = false>(options: Options<PatchV1SettingsData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchV1SettingsResponses, PatchV1SettingsErrors, ThrowOnError>({
        url: '/v1/settings',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
