// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type DbgenAction = {
    created_at: string;
    id: string;
    order: number;
    policy_id: string;
    type: string;
    updated_at: string;
    value: string;
};

export type DbgenCountImportTasksByStatusRow = {
    cancelled: number;
    completed: number;
    failed: number;
    in_progress: number;
    pending: number;
};

export type DbgenDownloadJob = {
    attempt_count: number;
    candidate_link: string;
    candidate_title: string;
    content_path: string;
    created_at: string;
    downloader_external_id: string;
    downloader_id: string;
    downloader_status: string;
    episode_id: string;
    error_category: string;
    guid: string;
    id: string;
    indexer_id: number;
    last_error: string;
    library_id: string;
    media_item_id: string;
    media_type: string;
    name_template_id: string;
    next_run_at: string;
    previous_job_id: string;
    progress: number;
    protocol: string;
    save_path: string;
    season_id: string;
    status: string;
    updated_at: string;
};

export type DbgenDownloader = {
    config_json: Array<number>;
    created_at: string;
    default: boolean;
    enabled: boolean;
    id: string;
    name: string;
    password: string;
    protocol: string;
    type: string;
    updated_at: string;
    url: string;
    username: string;
};

export type DbgenGetDownloadJobHistoryRow = {
    attempt_count: number;
    candidate_link: string;
    candidate_title: string;
    chain_depth: number;
    content_path: string;
    created_at: string;
    downloader_external_id: string;
    downloader_id: string;
    downloader_status: string;
    episode_id: string;
    error_category: string;
    guid: string;
    id: string;
    indexer_id: number;
    last_error: string;
    library_id: string;
    media_item_id: string;
    media_type: string;
    name_template_id: string;
    next_run_at: string;
    previous_job_id: string;
    progress: number;
    protocol: string;
    save_path: string;
    season_id: string;
    status: string;
    updated_at: string;
};

export type DbgenGetDownloadJobTimelineRow = {
    created_at: string;
    event_type: string;
    id: string;
    import_task_id: string;
    message: string;
    metadata: Array<number>;
    new_status: string;
    old_status: string;
    source: string;
};

export type DbgenGetDownloadJobWithImportSummaryRow = {
    active_imports: number;
    attempt_count: number;
    cancelled_imports: number;
    candidate_link: string;
    candidate_title: string;
    completed_imports: number;
    content_path: string;
    created_at: string;
    downloader_external_id: string;
    downloader_id: string;
    downloader_status: string;
    episode_id: string;
    episode_number: number;
    error_category: string;
    failed_imports: number;
    guid: string;
    id: string;
    import_status: string;
    indexer_id: number;
    last_error: string;
    library_id: string;
    media_item_id: string;
    media_type: string;
    name_template_id: string;
    next_run_at: string;
    pending_imports: number;
    previous_job_id: string;
    progress: number;
    protocol: string;
    save_path: string;
    season_id: string;
    season_number: number;
    status: string;
    tmdb_id: number;
    total_import_tasks: number;
    updated_at: string;
};

export type DbgenGetImportTaskHistoryRow = {
    attempt_count: number;
    chain_depth: number;
    created_at: string;
    dest_path: string;
    download_job_id: string;
    episode_id: string;
    error_category: string;
    id: string;
    import_method: string;
    last_error: string;
    library_id: string;
    max_attempts: number;
    media_file_id: string;
    media_item_id: string;
    media_type: string;
    name_template_id: string;
    next_run_at: string;
    previous_task_id: string;
    source_path: string;
    status: string;
    updated_at: string;
};

export type DbgenGetImportTaskWithDetailsRow = {
    attempt_count: number;
    candidate_title: string;
    created_at: string;
    dest_path: string;
    download_job_id: string;
    episode_id: string;
    episode_number: number;
    episode_title: string;
    error_category: string;
    id: string;
    import_method: string;
    last_error: string;
    library_id: string;
    library_name: string;
    library_root_path: string;
    max_attempts: number;
    media_file_id: string;
    media_item_id: string;
    media_item_type: string;
    media_title: string;
    media_tmdb_id: number;
    media_type: string;
    media_year: number;
    movie_dir_template: string;
    name_template: string;
    name_template_id: string;
    next_run_at: string;
    previous_task_id: string;
    season_number: number;
    series_season_template: string;
    series_show_template: string;
    source_path: string;
    status: string;
    updated_at: string;
};

export type DbgenImportTask = {
    attempt_count: number;
    created_at: string;
    dest_path: string;
    download_job_id: string;
    episode_id: string;
    error_category: string;
    id: string;
    import_method: string;
    last_error: string;
    library_id: string;
    max_attempts: number;
    media_file_id: string;
    media_item_id: string;
    media_type: string;
    name_template_id: string;
    next_run_at: string;
    previous_task_id: string;
    source_path: string;
    status: string;
    updated_at: string;
};

export type DbgenImportTaskEvent = {
    created_at: string;
    event_type: string;
    id: string;
    import_task_id: string;
    message: string;
    metadata: Array<number>;
    new_status: string;
    old_status: string;
};

export type DbgenListDownloadJobsByTmdbSeriesIdRow = {
    attempt_count: number;
    candidate_link: string;
    candidate_title: string;
    content_path: string;
    created_at: string;
    downloader_external_id: string;
    downloader_id: string;
    downloader_status: string;
    episode_id: string;
    episode_number: number;
    error_category: string;
    guid: string;
    id: string;
    indexer_id: number;
    last_error: string;
    library_id: string;
    media_item_id: string;
    media_type: string;
    name_template_id: string;
    next_run_at: string;
    previous_job_id: string;
    progress: number;
    protocol: string;
    save_path: string;
    season_id: string;
    season_number: number;
    status: string;
    updated_at: string;
};

export type DbgenListDownloadJobsWithImportSummaryRow = {
    active_imports: number;
    attempt_count: number;
    cancelled_imports: number;
    candidate_link: string;
    candidate_title: string;
    completed_imports: number;
    content_path: string;
    created_at: string;
    downloader_external_id: string;
    downloader_id: string;
    downloader_status: string;
    episode_id: string;
    episode_number: number;
    error_category: string;
    failed_imports: number;
    guid: string;
    id: string;
    import_status: string;
    indexer_id: number;
    last_error: string;
    library_id: string;
    media_item_id: string;
    media_type: string;
    name_template_id: string;
    next_run_at: string;
    pending_imports: number;
    previous_job_id: string;
    progress: number;
    protocol: string;
    save_path: string;
    season_id: string;
    season_number: number;
    status: string;
    tmdb_id: number;
    total_import_tasks: number;
    updated_at: string;
};

export type DbgenPolicy = {
    created_at: string;
    description: string;
    enabled: boolean;
    id: string;
    name: string;
    priority: number;
    updated_at: string;
};

export type DbgenRole = {
    built_in: boolean;
    created_at: string;
    description: string;
    id: string;
    name: string;
};

export type DbgenRule = {
    created_at: string;
    id: string;
    left_operand: string;
    operator: string;
    policy_id: string;
    right_operand: string;
    updated_at: string;
};

export type DownloaderTestResult = {
    error?: string;
    message: string;
    success: boolean;
    version?: string;
    webApiVersion?: string;
};

export type HandlersActionCreateRequest = {
    order: number;
    type: string;
    value: string;
};

export type HandlersActionUpdateRequest = {
    order: number;
    type: string;
    value: string;
};

export type HandlersBootstrapConfig = {
    signupStrategy: string;
    siteTitle: string;
    version: string;
};

export type HandlersBootstrapResponse = {
    config: HandlersBootstrapConfig;
    initialized: boolean;
    user: HandlersBootstrapUser;
};

export type HandlersBootstrapUser = {
    email: string;
    id: string;
    username: string;
};

export type HandlersDownloadCandidateResponse = {
    job: DbgenDownloadJob;
    trace: ModelEvaluationTrace;
};

export type HandlersDownloaderCreateRequest = {
    config_json: {
        [key: string]: unknown;
    };
    default: boolean;
    enabled: boolean;
    name: string;
    password: string;
    protocol: string;
    type: string;
    url: string;
    username: string;
};

export type HandlersDownloaderTestRequest = {
    config_json: {
        [key: string]: unknown;
    };
    password: string;
    type: string;
    url: string;
    username: string;
};

export type HandlersDownloaderUpdateRequest = {
    config_json: {
        [key: string]: unknown;
    };
    default: boolean;
    enabled: boolean;
    name: string;
    password: string;
    protocol: string;
    type: string;
    url: string;
    username: string;
};

export type HandlersEnqueueCandidateRequest = {
    episode?: number;
    guid: string;
    indexerId: number;
    season?: number;
};

export type HandlersInviteCreateRequest = {
    email: string;
};

export type HandlersLibraryCreateRequest = {
    default: boolean;
    enabled: boolean;
    name: string;
    root_path: string;
    type: string;
};

export type HandlersLibraryUpdateRequest = {
    default: boolean;
    enabled: boolean;
    name: string;
    root_path: string;
    type: string;
};

export type HandlersLoginRequest = {
    login: string;
    password: string;
};

export type HandlersLoginResponse = {
    token: string;
};

export type HandlersNameTemplateCreateRequest = {
    default: boolean;
    movie_dir_template: string;
    name: string;
    series_season_template: string;
    series_show_template: string;
    template: string;
    type: string;
};

export type HandlersNameTemplateUpdateRequest = {
    default: boolean;
    movie_dir_template: string;
    name: string;
    series_season_template: string;
    series_show_template: string;
    template: string;
    type: string;
};

export type HandlersPatchRequest = {
    key: string;
    value: unknown;
};

export type HandlersPlexExchangeRequest = {
    pin_id: number;
};

export type HandlersPlexExchangeResponse = {
    token: string;
};

export type HandlersPolicyCreateRequest = {
    description: string;
    enabled: boolean;
    name: string;
    priority: number;
};

export type HandlersPolicyUpdateRequest = {
    description: string;
    enabled: boolean;
    name: string;
    priority: number;
};

export type HandlersRuleCreateRequest = {
    left_operand: string;
    operator: string;
    right_operand: string;
};

export type HandlersRuleUpdateRequest = {
    left_operand: string;
    operator: string;
    right_operand: string;
};

export type HandlersSettingsListResponse = {
    [key: string]: unknown;
};

export type HandlersSetupInitializeRequest = {
    email: string;
    password: string;
    username: string;
};

export type HandlersSetupInitializeResponse = {
    success: boolean;
};

export type HandlersSetupStatusResponse = {
    initialized: boolean;
};

export type HandlersSignupRequest = {
    email: string;
    password: string;
    username: string;
};

export type HandlersSignupResponse = {
    success: boolean;
};

export type HandlersUnmatchedFileMatchRequest = {
    episode?: number;
    season?: number;
    tmdbId: number;
    type: string;
};

export type HandlersUserPasswordUpdateRequest = {
    password: string;
};

export type HandlersUserRoleUpdateRequest = {
    role: string;
};

export type HandlersUserUpdateRequest = {
    email: string;
    is_active: boolean;
    username: string;
};

export type HandlersFilesystemBrowseResponse = {
    current_path: string;
    directories: Array<HandlersFilesystemDirectoryEntry>;
    parent: string;
};

export type HandlersFilesystemDirectoryEntry = {
    name: string;
    path: string;
};

export type HandlersInviteSwagger = {
    claimed_at: string;
    created_at: string;
    email: string;
    id: string;
    invited_by: string;
};

export type HandlersLibrarySwagger = {
    created_at: string;
    default: boolean;
    enabled: boolean;
    id: string;
    name: string;
    root_path: string;
    type: string;
    updated_at: string;
};

export type HandlersNameTemplateSwagger = {
    created_at: string;
    default: boolean;
    id: string;
    movie_dir_template: string;
    name: string;
    series_season_template: string;
    series_show_template: string;
    template: string;
    type: string;
    updated_at: string;
};

export type HandlersUnmatchedFileSwagger = {
    discoveredAt: string;
    fileSize?: number;
    id: string;
    libraryId: string;
    path: string;
    suggestedMatches?: Array<ServiceSuggestedMatch>;
};

export type HandlersUnmatchedFilesListResponse = {
    items: Array<HandlersUnmatchedFileSwagger>;
    page: number;
    pageSize: number;
    totalCount: number;
};

export type HandlersUserSwagger = {
    created_at: string;
    email: string;
    id: string;
    is_active: boolean;
    roles: Array<string>;
    updated_at: string;
    username: string;
};

export type ModelActionInfo = {
    order: number;
    type: string;
    value: string;
};

export type ModelAvailability = {
    isInLibrary: boolean;
    libraries: Array<ModelLibraryAvailability>;
};

export type ModelCapabilities = {
    bookSearchParams: Array<string>;
    categories: Array<ModelCategories>;
    limitsDefault: number;
    limitsMax: number;
    movieSearchParams: Array<string>;
    musicSearchParams: Array<string>;
    searchParams: Array<string>;
    supportsRawSearch: boolean;
    tvSearchParams: Array<string>;
};

export type ModelCastMember = {
    /**
     * role name for cast
     */
    character: string;
    name: string;
    /**
     * for cast ordering
     */
    order: number;
    profilePath?: string;
    tmdbId: number;
};

export type ModelCategories = {
    id: number;
    name: string;
    subCategories: Array<ModelCategories>;
};

export type ModelContextSnapshot = {
    candidate: {
        [key: string]: unknown;
    };
    media: {
        [key: string]: unknown;
    };
    mediainfo?: {
        [key: string]: unknown;
    };
    quality: {
        [key: string]: unknown;
    };
    release: {
        [key: string]: unknown;
    };
};

export type ModelCredits = {
    cast: Array<ModelCastMember>;
    crew: Array<ModelCrewMember>;
};

export type ModelCrewMember = {
    /**
     * e.g., "Directing", "Production"
     */
    department: string;
    /**
     * e.g., "Director", "Producer"
     */
    job: string;
    name: string;
    profilePath?: string;
    tmdbId: number;
};

export type ModelDownloadCandidate = {
    /**
     * age in seconds
     */
    age: number;
    ageHours: number;
    categories: Array<string>;
    filename: string;
    grabs: number;
    guid: string;
    indexer: string;
    indexerFlags: Array<string>;
    indexerId: number;
    link: string;
    /**
     * leechers
     */
    peers: number;
    protocol: string;
    publishDate: string;
    /**
     * seeders
     */
    seeders: number;
    /**
     * size in bytes
     */
    size: number;
    title: string;
};

export type ModelEnumValue = {
    label: string;
    value: string;
};

export type ModelEpisodeAvailability = {
    airDate?: string;
    available: boolean;
    episodeNumber: number;
    file?: ModelFileInfo;
    overview?: string;
    seasonNumber: number;
    stillPath?: string;
    title?: string;
};

export type ModelEvaluationTrace = {
    /**
     * Full evaluation context for debugging
     */
    context?: ModelContextSnapshot;
    finalPlan: ModelPlan;
    policies: Array<ModelPolicyEvaluation>;
};

export type ModelFeed = {
    hero?: ModelHeroItem;
    rows: Array<ModelFeedRow>;
};

export type ModelFeedRow = {
    id: string;
    items: Array<ModelHydratedTitle>;
    subtitle?: string;
    title: string;
};

export type ModelFieldDefinition = {
    /**
     * API endpoint for dynamic fields
     */
    dynamicSource?: string;
    /**
     * For enum type
     */
    enumValues?: Array<ModelEnumValue>;
    /**
     * Display name
     */
    label: string;
    /**
     * Valid operators for this field
     */
    operators: Array<string>;
    /**
     * e.g., "candidate.size", "quality.resolution"
     */
    path: string;
    /**
     * "text", "number", "enum", "dynamic", "boolean"
     */
    type: ModelFieldType;
    /**
     * "string", "int64", "float64", "[]string", "bool"
     */
    valueType: string;
};

export type ModelFieldInput = {
    name: string;
    value?: unknown;
};

export type ModelFieldOutput = {
    advanced?: boolean;
    helpLink?: string;
    helpText?: string;
    hidden?: string;
    label?: string;
    name: string;
    order?: number;
    privacy: string;
    selectOptions?: Array<ModelSelectOption>;
    selectOptionsProviderAction?: string;
    type?: string;
    value?: unknown;
};

export type ModelFieldType = 'text' | 'number' | 'enum' | 'dynamic' | 'boolean';

export type ModelFileInfo = {
    /**
     * For matching with download jobs store
     */
    downloadJobId?: string;
    episodeNumber?: number;
    id: string;
    libraryId: string;
    /**
     * relative to library root
     */
    path: string;
    /**
     * Progress 0-1 for downloading files
     */
    progress?: number;
    seasonNumber?: number;
    status: string;
};

export type ModelGenre = {
    name: string;
    tmdbId: number;
};

export type ModelHeroItem = {
    backdropPath: string;
    mediaType: string;
    overview: string;
    posterPath: string;
    title: string;
    tmdbId: number;
    trailerUrl?: string;
};

export type ModelHydratedTitle = {
    backdropPath?: string;
    genreIds?: Array<number>;
    isDownloading?: boolean;
    isInLibrary?: boolean;
    language?: string;
    /**
     * "movie" or "series"
     */
    mediaType: ModelMediaType;
    overview: string;
    popularity?: number;
    posterPath: string;
    releaseDate: string;
    title: string;
    tmdbId: number;
    voteAverage?: number;
    year?: number;
};

export type ModelIndexerBatchTestResult = {
    error?: string;
    indexer_id: number;
    indexer_name: string;
    message?: string;
    success: boolean;
};

export type ModelIndexerCapabilities = {
    bookSearchParams: Array<string>;
    categories: Array<ModelIndexerCategory>;
    limitsDefault: number;
    limitsMax: number;
    movieSearchParams: Array<string>;
    musicSearchParams: Array<string>;
    searchParams: Array<string>;
    supportsRawSearch: boolean;
    tvSearchParams: Array<string>;
};

export type ModelIndexerCategory = {
    id: number;
    name: string;
    subCategories: Array<ModelIndexerCategory>;
};

export type ModelIndexerDefinition = {
    added: string;
    appProfileId: number;
    capabilities: ModelIndexerCapabilities;
    configContract: string;
    definitionName: string;
    description: string;
    downloadClientId: number;
    enable: boolean;
    encoding: string;
    fields: Array<ModelIndexerField>;
    implementation: string;
    implementationName: string;
    indexerUrls: Array<string>;
    infoLink: string;
    language: string;
    legacyUrls: Array<string>;
    name: string;
    presets: Array<unknown>;
    priority: number;
    privacy: string;
    protocol: string;
    redirect: boolean;
    sortName: string;
    supportsPagination: boolean;
    supportsRedirect: boolean;
    supportsRss: boolean;
    supportsSearch: boolean;
    tags: Array<string>;
};

export type ModelIndexerField = {
    advanced: boolean;
    helpLink?: string;
    helpText?: string;
    helpTextWarning?: string;
    hidden?: string;
    isFloat: boolean;
    label: string;
    name: string;
    order: number;
    privacy: string;
    selectOptions?: Array<ModelIndexerSelectOption>;
    selectOptionsProviderAction?: string;
    type: string;
    unit?: string;
    value?: unknown;
};

export type ModelIndexerInput = {
    appProfileId: number;
    configContract: string;
    enable: boolean;
    fields: Array<ModelFieldInput>;
    id?: number;
    implementation: string;
    name: string;
    priority: number;
    protocol: ModelProtocol;
    redirect: boolean;
    tags?: Array<number>;
};

export type ModelIndexerOutput = {
    added: string;
    appProfileId: number;
    capabilities?: ModelCapabilities;
    configContract: string;
    definitionName: string;
    description: string;
    enable: boolean;
    encoding?: string;
    fields: Array<ModelFieldOutput>;
    id?: number;
    implementation: string;
    implementationName: string;
    indexerUrls: Array<string>;
    infoLink: string;
    language: string;
    legacyUrls: Array<string>;
    name: string;
    priority: number;
    privacy: string;
    protocol: ModelProtocol;
    redirect: boolean;
    sortName: string;
    supportsRedirect: boolean;
    supportsRss: boolean;
    supportsSearch: boolean;
    tags: Array<number>;
};

export type ModelIndexerSelectOption = {
    hint?: string;
    name: string;
    order: number;
    value: unknown;
};

export type ModelIndexerTestResult = {
    error?: string;
    message?: string;
    success: boolean;
};

export type ModelLibraryAvailability = {
    fileCount: number;
    libraryId: string;
    statusRollup: string;
};

export type ModelLibraryItem = {
    createdAt: string;
    id: string;
    posterPath?: string;
    title: string;
    tmdbId?: number;
    type: string;
    year?: number;
};

export type ModelMediaType = 'movie' | 'series';

export type ModelMovieDetail = {
    backdropPath?: string;
    certification?: string;
    credits?: ModelCredits;
    files: Array<ModelFileInfo>;
    genres?: Array<ModelGenre>;
    overview: string;
    posterPath?: string;
    recommendations?: Array<ModelMovieRail>;
    releaseDate?: string;
    runtime?: number;
    status: string;
    tagline?: string;
    title: string;
    tmdbId: number;
    videos?: Array<ModelVideo>;
    watchProviders?: ModelWatchProviders;
    year?: number;
};

export type ModelMovieRail = {
    genres?: Array<number>;
    isDownloading: boolean;
    isInLibrary: boolean;
    overview: string;
    posterPath: string;
    releaseDate: string;
    tagline?: string;
    title: string;
    tmdbId: number;
    year?: number;
};

export type ModelPaginatedLibraryResponse = {
    data: Array<ModelLibraryItem>;
    pagination: ModelPagination;
};

export type ModelPagination = {
    page: number;
    pageSize: number;
    total: number;
    totalPages: number;
};

export type ModelPersonDetail = {
    alsoKnownAs?: Array<string>;
    biography: string;
    birthday?: string;
    deathday?: string;
    homepage?: string;
    imdbId?: string;
    knownForDepartment: string;
    name: string;
    placeOfBirth?: string;
    popularity: number;
    profilePath?: string;
    tmdbId: number;
};

export type ModelPlan = {
    /**
     * how to download
     */
    downloaderId: string;
    /**
     * where to move/hardlink/copy the file to
     */
    libraryId: string;
    /**
     * how to name the file
     */
    nameTemplateId: string;
};

export type ModelPolicyEvaluation = {
    actionsApplied: Array<ModelActionInfo>;
    matched: boolean;
    policyId: string;
    policyName: string;
    priority: number;
    ruleEvaluated?: ModelRuleInfo;
    stoppedProcessing: boolean;
};

export type ModelProtocol = 'unknown' | 'usenet' | 'torrent';

export type ModelRuleInfo = {
    leftOperand: string;
    /**
     * Resolved value of left operand
     */
    leftResolvedValue?: unknown;
    operator: string;
    rightOperand: string;
    /**
     * Resolved value of right operand
     */
    rightResolvedValue?: unknown;
};

export type ModelSearchResponse = {
    query: string;
    results: Array<ModelSearchResult>;
    totalResults: number;
};

export type ModelSearchResult = {
    id: number;
    isInLibrary: boolean;
    /**
     * "movie", "tv", "person"
     */
    mediaType: string;
    overview?: string;
    posterPath?: string;
    title: string;
    year?: number;
};

export type ModelSeasonDetail = {
    airDate?: string;
    episodes: Array<ModelEpisodeAvailability>;
    overview?: string;
    posterPath?: string;
    seasonNumber: number;
};

export type ModelSelectOption = {
    dividerAfter?: boolean;
    hint: string;
    name: string;
    order: number;
    value: number;
};

export type ModelSeriesDetail = {
    availability: ModelAvailability;
    backdropPath?: string;
    certification?: string;
    credits?: ModelCredits;
    episodeRuntime?: number;
    firstAirDate?: string;
    genres?: Array<ModelGenre>;
    inProduction: boolean;
    lastAirDate?: string;
    overview: string;
    posterPath?: string;
    seasons: Array<ModelSeasonDetail>;
    status: string;
    tagline?: string;
    title: string;
    tmdbId: number;
    videos?: Array<ModelVideo>;
    watchProviders?: ModelWatchProviders;
    year?: number;
};

export type ModelVideo = {
    isOfficialTrailer: boolean;
    /**
     * YouTube/Vimeo video ID
     */
    key: string;
    name: string;
    publishedAt?: string;
    /**
     * "YouTube", "Vimeo", etc.
     */
    site: string;
    /**
     * 360, 480, 720, 1080
     */
    size: number;
    tmdbId: string;
    /**
     * "Trailer", "Teaser", "Clip", etc.
     */
    type: string;
};

export type ModelWatchProvider = {
    displayPriority: number;
    logoPath: string;
    providerId: number;
    providerName: string;
};

export type ModelWatchProviders = {
    buy?: Array<ModelWatchProvider>;
    flatrate?: Array<ModelWatchProvider>;
    link?: string;
    rent?: Array<ModelWatchProvider>;
};

export type ServiceLatestVersionInfo = {
    commit?: string;
    notes?: string;
    publishedAt?: string;
    ref?: string;
    tag: string;
    url: string;
    version: string;
};

export type ServiceReimportResult = {
    created_tasks: Array<DbgenImportTask>;
    skipped_count: number;
};

export type ServiceSuggestedMatch = {
    score: number;
    title: string;
    tmdbId: number;
    /**
     * movie or series
     */
    type: string;
    year?: number;
};

export type ServiceUpdateDetails = {
    latest?: ServiceLatestVersionInfo;
    reason?: string;
    status: ServiceUpdateStatus;
};

export type ServiceUpdateStatus = 'up_to_date' | 'update_available' | 'unknown';

export type ServiceVersionInfo = {
    buildDate?: string;
    commit?: string;
    components?: {
        [key: string]: string;
    };
    update: ServiceUpdateDetails;
    version: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * ok
     */
    200: string;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type PostV1AuthLoginData = {
    /**
     * Login request
     */
    body: HandlersLoginRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type PostV1AuthLoginResponses = {
    /**
     * OK
     */
    200: HandlersLoginResponse;
};

export type PostV1AuthLoginResponse = PostV1AuthLoginResponses[keyof PostV1AuthLoginResponses];

export type PostV1AuthPlexExchangeData = {
    /**
     * Plex exchange request
     */
    body: HandlersPlexExchangeRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/plex/exchange';
};

export type PostV1AuthPlexExchangeErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Unauthorized
     */
    401: {
        [key: string]: string;
    };
    /**
     * Forbidden
     */
    403: {
        [key: string]: string;
    };
    /**
     * Conflict
     */
    409: {
        [key: string]: string;
    };
};

export type PostV1AuthPlexExchangeError = PostV1AuthPlexExchangeErrors[keyof PostV1AuthPlexExchangeErrors];

export type PostV1AuthPlexExchangeResponses = {
    /**
     * OK
     */
    200: HandlersPlexExchangeResponse;
};

export type PostV1AuthPlexExchangeResponse = PostV1AuthPlexExchangeResponses[keyof PostV1AuthPlexExchangeResponses];

export type GetV1AuthProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/auth/profile';
};

export type GetV1AuthProfileResponses = {
    /**
     * OK
     */
    200: HandlersUserSwagger;
};

export type GetV1AuthProfileResponse = GetV1AuthProfileResponses[keyof GetV1AuthProfileResponses];

export type PutV1AuthProfileData = {
    /**
     * Update profile
     */
    body: HandlersUserUpdateRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/profile';
};

export type PutV1AuthProfileResponses = {
    /**
     * OK
     */
    200: HandlersUserSwagger;
};

export type PutV1AuthProfileResponse = PutV1AuthProfileResponses[keyof PutV1AuthProfileResponses];

export type PutV1AuthProfilePasswordData = {
    /**
     * Update password
     */
    body: HandlersUserPasswordUpdateRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/profile/password';
};

export type PutV1AuthProfilePasswordResponses = {
    /**
     * No Content
     */
    204: string;
};

export type PutV1AuthProfilePasswordResponse = PutV1AuthProfilePasswordResponses[keyof PutV1AuthProfilePasswordResponses];

export type PostV1AuthSignupData = {
    /**
     * Signup request
     */
    body: HandlersSignupRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/signup';
};

export type PostV1AuthSignupErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Forbidden
     */
    403: {
        [key: string]: string;
    };
    /**
     * Conflict
     */
    409: {
        [key: string]: string;
    };
};

export type PostV1AuthSignupError = PostV1AuthSignupErrors[keyof PostV1AuthSignupErrors];

export type PostV1AuthSignupResponses = {
    /**
     * Created
     */
    201: HandlersSignupResponse;
};

export type PostV1AuthSignupResponse = PostV1AuthSignupResponses[keyof PostV1AuthSignupResponses];

export type GetV1BootstrapData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/bootstrap';
};

export type GetV1BootstrapResponses = {
    /**
     * OK
     */
    200: HandlersBootstrapResponse;
};

export type GetV1BootstrapResponse = GetV1BootstrapResponses[keyof GetV1BootstrapResponses];

export type GetV1DownloadJobsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/download-jobs';
};

export type GetV1DownloadJobsResponses = {
    /**
     * OK
     */
    200: Array<DbgenListDownloadJobsWithImportSummaryRow>;
};

export type GetV1DownloadJobsResponse = GetV1DownloadJobsResponses[keyof GetV1DownloadJobsResponses];

export type DeleteV1DownloadJobsByIdData = {
    body?: never;
    path: {
        /**
         * Job ID (uuid)
         */
        id: string;
    };
    query?: never;
    url: '/v1/download-jobs/{id}';
};

export type DeleteV1DownloadJobsByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type DeleteV1DownloadJobsByIdError = DeleteV1DownloadJobsByIdErrors[keyof DeleteV1DownloadJobsByIdErrors];

export type DeleteV1DownloadJobsByIdResponses = {
    /**
     * OK
     */
    200: DbgenDownloadJob;
};

export type DeleteV1DownloadJobsByIdResponse = DeleteV1DownloadJobsByIdResponses[keyof DeleteV1DownloadJobsByIdResponses];

export type GetV1DownloadJobsByIdData = {
    body?: never;
    path: {
        /**
         * Job ID (uuid)
         */
        id: string;
    };
    query?: never;
    url: '/v1/download-jobs/{id}';
};

export type GetV1DownloadJobsByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type GetV1DownloadJobsByIdError = GetV1DownloadJobsByIdErrors[keyof GetV1DownloadJobsByIdErrors];

export type GetV1DownloadJobsByIdResponses = {
    /**
     * OK
     */
    200: DbgenGetDownloadJobWithImportSummaryRow;
};

export type GetV1DownloadJobsByIdResponse = GetV1DownloadJobsByIdResponses[keyof GetV1DownloadJobsByIdResponses];

export type GetV1DownloadJobsByIdHistoryData = {
    body?: never;
    path: {
        /**
         * Job ID (uuid)
         */
        id: string;
    };
    query?: never;
    url: '/v1/download-jobs/{id}/history';
};

export type GetV1DownloadJobsByIdHistoryErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type GetV1DownloadJobsByIdHistoryError = GetV1DownloadJobsByIdHistoryErrors[keyof GetV1DownloadJobsByIdHistoryErrors];

export type GetV1DownloadJobsByIdHistoryResponses = {
    /**
     * OK
     */
    200: Array<DbgenGetDownloadJobHistoryRow>;
};

export type GetV1DownloadJobsByIdHistoryResponse = GetV1DownloadJobsByIdHistoryResponses[keyof GetV1DownloadJobsByIdHistoryResponses];

export type GetV1DownloadJobsByIdImportTasksData = {
    body?: never;
    path: {
        /**
         * Job ID (uuid)
         */
        id: string;
    };
    query?: never;
    url: '/v1/download-jobs/{id}/import-tasks';
};

export type GetV1DownloadJobsByIdImportTasksErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type GetV1DownloadJobsByIdImportTasksError = GetV1DownloadJobsByIdImportTasksErrors[keyof GetV1DownloadJobsByIdImportTasksErrors];

export type GetV1DownloadJobsByIdImportTasksResponses = {
    /**
     * OK
     */
    200: Array<DbgenImportTask>;
};

export type GetV1DownloadJobsByIdImportTasksResponse = GetV1DownloadJobsByIdImportTasksResponses[keyof GetV1DownloadJobsByIdImportTasksResponses];

export type PostV1DownloadJobsByIdReimportData = {
    body?: never;
    path: {
        /**
         * Job ID (uuid)
         */
        id: string;
    };
    query?: {
        /**
         * Reimport all tasks, not just failed ones
         */
        all?: boolean;
    };
    url: '/v1/download-jobs/{id}/reimport';
};

export type PostV1DownloadJobsByIdReimportErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type PostV1DownloadJobsByIdReimportError = PostV1DownloadJobsByIdReimportErrors[keyof PostV1DownloadJobsByIdReimportErrors];

export type PostV1DownloadJobsByIdReimportResponses = {
    /**
     * OK
     */
    200: ServiceReimportResult;
};

export type PostV1DownloadJobsByIdReimportResponse = PostV1DownloadJobsByIdReimportResponses[keyof PostV1DownloadJobsByIdReimportResponses];

export type PostV1DownloadJobsByIdRetryData = {
    body?: never;
    path: {
        /**
         * Job ID (uuid)
         */
        id: string;
    };
    query?: never;
    url: '/v1/download-jobs/{id}/retry';
};

export type PostV1DownloadJobsByIdRetryErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Conflict
     */
    409: {
        [key: string]: string;
    };
};

export type PostV1DownloadJobsByIdRetryError = PostV1DownloadJobsByIdRetryErrors[keyof PostV1DownloadJobsByIdRetryErrors];

export type PostV1DownloadJobsByIdRetryResponses = {
    /**
     * OK
     */
    200: DbgenGetDownloadJobWithImportSummaryRow;
};

export type PostV1DownloadJobsByIdRetryResponse = PostV1DownloadJobsByIdRetryResponses[keyof PostV1DownloadJobsByIdRetryResponses];

export type GetV1DownloadJobsByIdTimelineData = {
    body?: never;
    path: {
        /**
         * Job ID (uuid)
         */
        id: string;
    };
    query?: never;
    url: '/v1/download-jobs/{id}/timeline';
};

export type GetV1DownloadJobsByIdTimelineErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type GetV1DownloadJobsByIdTimelineError = GetV1DownloadJobsByIdTimelineErrors[keyof GetV1DownloadJobsByIdTimelineErrors];

export type GetV1DownloadJobsByIdTimelineResponses = {
    /**
     * OK
     */
    200: Array<DbgenGetDownloadJobTimelineRow>;
};

export type GetV1DownloadJobsByIdTimelineResponse = GetV1DownloadJobsByIdTimelineResponses[keyof GetV1DownloadJobsByIdTimelineResponses];

export type GetV1DownloadersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/downloaders';
};

export type GetV1DownloadersResponses = {
    /**
     * OK
     */
    200: Array<DbgenDownloader>;
};

export type GetV1DownloadersResponse = GetV1DownloadersResponses[keyof GetV1DownloadersResponses];

export type PostV1DownloadersData = {
    /**
     * Create downloader
     */
    body: HandlersDownloaderCreateRequest;
    path?: never;
    query?: never;
    url: '/v1/downloaders';
};

export type PostV1DownloadersErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1DownloadersError = PostV1DownloadersErrors[keyof PostV1DownloadersErrors];

export type PostV1DownloadersResponses = {
    /**
     * Created
     */
    201: DbgenDownloader;
};

export type PostV1DownloadersResponse = PostV1DownloadersResponses[keyof PostV1DownloadersResponses];

export type GetV1DownloadersDefaultByProtocolData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/downloaders/default/{protocol}';
};

export type GetV1DownloadersDefaultByProtocolResponses = {
    /**
     * OK
     */
    200: DbgenDownloader;
};

export type GetV1DownloadersDefaultByProtocolResponse = GetV1DownloadersDefaultByProtocolResponses[keyof GetV1DownloadersDefaultByProtocolResponses];

export type PostV1DownloadersTestData = {
    /**
     * Test downloader configuration
     */
    body: HandlersDownloaderTestRequest;
    path?: never;
    query?: never;
    url: '/v1/downloaders/test';
};

export type PostV1DownloadersTestErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1DownloadersTestError = PostV1DownloadersTestErrors[keyof PostV1DownloadersTestErrors];

export type PostV1DownloadersTestResponses = {
    /**
     * OK
     */
    200: DownloaderTestResult;
};

export type PostV1DownloadersTestResponse = PostV1DownloadersTestResponses[keyof PostV1DownloadersTestResponses];

export type DeleteV1DownloadersByIdData = {
    body?: never;
    path: {
        /**
         * Downloader ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/downloaders/{id}';
};

export type DeleteV1DownloadersByIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1DownloadersByIdResponse = DeleteV1DownloadersByIdResponses[keyof DeleteV1DownloadersByIdResponses];

export type GetV1DownloadersByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/downloaders/{id}';
};

export type GetV1DownloadersByIdResponses = {
    /**
     * OK
     */
    200: DbgenDownloader;
};

export type GetV1DownloadersByIdResponse = GetV1DownloadersByIdResponses[keyof GetV1DownloadersByIdResponses];

export type PutV1DownloadersByIdData = {
    /**
     * Update downloader
     */
    body: HandlersDownloaderUpdateRequest;
    path: {
        /**
         * Downloader ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/downloaders/{id}';
};

export type PutV1DownloadersByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1DownloadersByIdError = PutV1DownloadersByIdErrors[keyof PutV1DownloadersByIdErrors];

export type PutV1DownloadersByIdResponses = {
    /**
     * OK
     */
    200: DbgenDownloader;
};

export type PutV1DownloadersByIdResponse = PutV1DownloadersByIdResponses[keyof PutV1DownloadersByIdResponses];

export type PostV1DownloadersByIdTestData = {
    body?: never;
    path: {
        /**
         * Downloader ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/downloaders/{id}/test';
};

export type PostV1DownloadersByIdTestErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type PostV1DownloadersByIdTestError = PostV1DownloadersByIdTestErrors[keyof PostV1DownloadersByIdTestErrors];

export type PostV1DownloadersByIdTestResponses = {
    /**
     * OK
     */
    200: DownloaderTestResult;
};

export type PostV1DownloadersByIdTestResponse = PostV1DownloadersByIdTestResponses[keyof PostV1DownloadersByIdTestResponses];

export type GetV1FilesystemBrowseData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Directory path to browse (defaults to /)
         */
        path?: string;
    };
    url: '/v1/filesystem/browse';
};

export type GetV1FilesystemBrowseErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Forbidden
     */
    403: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type GetV1FilesystemBrowseError = GetV1FilesystemBrowseErrors[keyof GetV1FilesystemBrowseErrors];

export type GetV1FilesystemBrowseResponses = {
    /**
     * OK
     */
    200: HandlersFilesystemBrowseResponse;
};

export type GetV1FilesystemBrowseResponse = GetV1FilesystemBrowseResponses[keyof GetV1FilesystemBrowseResponses];

export type GetV1HomeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/home';
};

export type GetV1HomeResponses = {
    /**
     * OK
     */
    200: ModelFeed;
};

export type GetV1HomeResponse = GetV1HomeResponses[keyof GetV1HomeResponses];

export type GetV1ImportTasksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by status
         */
        status?: string;
        /**
         * Page size
         */
        limit?: number;
        /**
         * Page offset
         */
        offset?: number;
    };
    url: '/v1/import-tasks';
};

export type GetV1ImportTasksResponses = {
    /**
     * OK
     */
    200: Array<DbgenImportTask>;
};

export type GetV1ImportTasksResponse = GetV1ImportTasksResponses[keyof GetV1ImportTasksResponses];

export type GetV1ImportTasksCountsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/import-tasks/counts';
};

export type GetV1ImportTasksCountsResponses = {
    /**
     * OK
     */
    200: DbgenCountImportTasksByStatusRow;
};

export type GetV1ImportTasksCountsResponse = GetV1ImportTasksCountsResponses[keyof GetV1ImportTasksCountsResponses];

export type GetV1ImportTasksByIdData = {
    body?: never;
    path: {
        /**
         * Task ID (uuid)
         */
        id: string;
    };
    query?: never;
    url: '/v1/import-tasks/{id}';
};

export type GetV1ImportTasksByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type GetV1ImportTasksByIdError = GetV1ImportTasksByIdErrors[keyof GetV1ImportTasksByIdErrors];

export type GetV1ImportTasksByIdResponses = {
    /**
     * OK
     */
    200: DbgenGetImportTaskWithDetailsRow;
};

export type GetV1ImportTasksByIdResponse = GetV1ImportTasksByIdResponses[keyof GetV1ImportTasksByIdResponses];

export type PostV1ImportTasksByIdCancelData = {
    body?: never;
    path: {
        /**
         * Task ID (uuid)
         */
        id: string;
    };
    query?: never;
    url: '/v1/import-tasks/{id}/cancel';
};

export type PostV1ImportTasksByIdCancelErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1ImportTasksByIdCancelError = PostV1ImportTasksByIdCancelErrors[keyof PostV1ImportTasksByIdCancelErrors];

export type PostV1ImportTasksByIdCancelResponses = {
    /**
     * OK
     */
    200: DbgenImportTask;
};

export type PostV1ImportTasksByIdCancelResponse = PostV1ImportTasksByIdCancelResponses[keyof PostV1ImportTasksByIdCancelResponses];

export type GetV1ImportTasksByIdHistoryData = {
    body?: never;
    path: {
        /**
         * Task ID (uuid)
         */
        id: string;
    };
    query?: never;
    url: '/v1/import-tasks/{id}/history';
};

export type GetV1ImportTasksByIdHistoryErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type GetV1ImportTasksByIdHistoryError = GetV1ImportTasksByIdHistoryErrors[keyof GetV1ImportTasksByIdHistoryErrors];

export type GetV1ImportTasksByIdHistoryResponses = {
    /**
     * OK
     */
    200: Array<DbgenGetImportTaskHistoryRow>;
};

export type GetV1ImportTasksByIdHistoryResponse = GetV1ImportTasksByIdHistoryResponses[keyof GetV1ImportTasksByIdHistoryResponses];

export type PostV1ImportTasksByIdReimportData = {
    body?: never;
    path: {
        /**
         * Task ID (uuid)
         */
        id: string;
    };
    query?: never;
    url: '/v1/import-tasks/{id}/reimport';
};

export type PostV1ImportTasksByIdReimportErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type PostV1ImportTasksByIdReimportError = PostV1ImportTasksByIdReimportErrors[keyof PostV1ImportTasksByIdReimportErrors];

export type PostV1ImportTasksByIdReimportResponses = {
    /**
     * OK
     */
    200: DbgenImportTask;
};

export type PostV1ImportTasksByIdReimportResponse = PostV1ImportTasksByIdReimportResponses[keyof PostV1ImportTasksByIdReimportResponses];

export type GetV1ImportTasksByIdTimelineData = {
    body?: never;
    path: {
        /**
         * Task ID (uuid)
         */
        id: string;
    };
    query?: never;
    url: '/v1/import-tasks/{id}/timeline';
};

export type GetV1ImportTasksByIdTimelineErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type GetV1ImportTasksByIdTimelineError = GetV1ImportTasksByIdTimelineErrors[keyof GetV1ImportTasksByIdTimelineErrors];

export type GetV1ImportTasksByIdTimelineResponses = {
    /**
     * OK
     */
    200: Array<DbgenImportTaskEvent>;
};

export type GetV1ImportTasksByIdTimelineResponse = GetV1ImportTasksByIdTimelineResponses[keyof GetV1ImportTasksByIdTimelineResponses];

export type PostV1IndexerData = {
    /**
     * Save indexer
     */
    body: ModelIndexerInput;
    path?: never;
    query?: never;
    url: '/v1/indexer';
};

export type PostV1IndexerErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1IndexerError = PostV1IndexerErrors[keyof PostV1IndexerErrors];

export type PostV1IndexerResponses = {
    /**
     * OK
     */
    200: ModelIndexerOutput;
};

export type PostV1IndexerResponse = PostV1IndexerResponses[keyof PostV1IndexerResponses];

export type PostV1IndexerActionByNameData = {
    body?: never;
    path: {
        /**
         * Action name
         */
        name: string;
    };
    query?: never;
    url: '/v1/indexer/action/{name}';
};

export type PostV1IndexerActionByNameErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1IndexerActionByNameError = PostV1IndexerActionByNameErrors[keyof PostV1IndexerActionByNameErrors];

export type PostV1IndexerActionByNameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostV1IndexerTestData = {
    /**
     * Indexer config
     */
    body: ModelIndexerInput;
    path?: never;
    query?: never;
    url: '/v1/indexer/test';
};

export type PostV1IndexerTestErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1IndexerTestError = PostV1IndexerTestErrors[keyof PostV1IndexerTestErrors];

export type PostV1IndexerTestResponses = {
    /**
     * OK
     */
    200: ModelIndexerTestResult;
};

export type PostV1IndexerTestResponse = PostV1IndexerTestResponses[keyof PostV1IndexerTestResponses];

export type DeleteV1IndexerByIdData = {
    body?: never;
    path: {
        /**
         * Indexer ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/indexer/{id}';
};

export type DeleteV1IndexerByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type DeleteV1IndexerByIdError = DeleteV1IndexerByIdErrors[keyof DeleteV1IndexerByIdErrors];

export type DeleteV1IndexerByIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1IndexerByIdResponse = DeleteV1IndexerByIdResponses[keyof DeleteV1IndexerByIdResponses];

export type PostV1IndexerByIdTestData = {
    body?: never;
    path: {
        /**
         * Indexer ID
         */
        id: number;
    };
    query?: never;
    url: '/v1/indexer/{id}/test';
};

export type PostV1IndexerByIdTestErrors = {
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1IndexerByIdTestError = PostV1IndexerByIdTestErrors[keyof PostV1IndexerByIdTestErrors];

export type PostV1IndexerByIdTestResponses = {
    /**
     * OK
     */
    200: ModelIndexerTestResult;
};

export type PostV1IndexerByIdTestResponse = PostV1IndexerByIdTestResponses[keyof PostV1IndexerByIdTestResponses];

export type PutV1IndexerByIdToggleData = {
    body?: never;
    path: {
        /**
         * Indexer ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/indexer/{id}/toggle';
};

export type PutV1IndexerByIdToggleErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PutV1IndexerByIdToggleError = PutV1IndexerByIdToggleErrors[keyof PutV1IndexerByIdToggleErrors];

export type PutV1IndexerByIdToggleResponses = {
    /**
     * OK
     */
    200: ModelIndexerOutput;
};

export type PutV1IndexerByIdToggleResponse = PutV1IndexerByIdToggleResponses[keyof PutV1IndexerByIdToggleResponses];

export type GetV1IndexersConfiguredData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/indexers/configured';
};

export type GetV1IndexersConfiguredResponses = {
    /**
     * OK
     */
    200: Array<ModelIndexerOutput>;
};

export type GetV1IndexersConfiguredResponse = GetV1IndexersConfiguredResponses[keyof GetV1IndexersConfiguredResponses];

export type GetV1IndexersSchemaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/indexers/schema';
};

export type GetV1IndexersSchemaResponses = {
    /**
     * OK
     */
    200: Array<Array<ModelIndexerDefinition>>;
};

export type GetV1IndexersSchemaResponse = GetV1IndexersSchemaResponses[keyof GetV1IndexersSchemaResponses];

export type PostV1IndexersTestallData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/indexers/testall';
};

export type PostV1IndexersTestallErrors = {
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1IndexersTestallError = PostV1IndexersTestallErrors[keyof PostV1IndexersTestallErrors];

export type PostV1IndexersTestallResponses = {
    /**
     * OK
     */
    200: Array<ModelIndexerBatchTestResult>;
};

export type PostV1IndexersTestallResponse = PostV1IndexersTestallResponses[keyof PostV1IndexersTestallResponses];

export type GetV1IndexersByIdData = {
    body?: never;
    path: {
        /**
         * Indexer ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/indexers/{id}';
};

export type GetV1IndexersByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetV1IndexersByIdError = GetV1IndexersByIdErrors[keyof GetV1IndexersByIdErrors];

export type GetV1IndexersByIdResponses = {
    /**
     * OK
     */
    200: ModelIndexerOutput;
};

export type GetV1IndexersByIdResponse = GetV1IndexersByIdResponses[keyof GetV1IndexersByIdResponses];

export type GetV1InvitesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/invites';
};

export type GetV1InvitesResponses = {
    /**
     * OK
     */
    200: Array<HandlersInviteSwagger>;
};

export type GetV1InvitesResponse = GetV1InvitesResponses[keyof GetV1InvitesResponses];

export type PostV1InvitesData = {
    /**
     * Create invite
     */
    body: HandlersInviteCreateRequest;
    path?: never;
    query?: never;
    url: '/v1/invites';
};

export type PostV1InvitesErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1InvitesError = PostV1InvitesErrors[keyof PostV1InvitesErrors];

export type PostV1InvitesResponses = {
    /**
     * Created
     */
    201: HandlersInviteSwagger;
};

export type PostV1InvitesResponse = PostV1InvitesResponses[keyof PostV1InvitesResponses];

export type DeleteV1InvitesByIdData = {
    body?: never;
    path: {
        /**
         * Invite ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/invites/{id}';
};

export type DeleteV1InvitesByIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1InvitesByIdResponse = DeleteV1InvitesByIdResponses[keyof DeleteV1InvitesByIdResponses];

export type GetV1LibrariesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/libraries';
};

export type GetV1LibrariesResponses = {
    /**
     * OK
     */
    200: Array<HandlersLibrarySwagger>;
};

export type GetV1LibrariesResponse = GetV1LibrariesResponses[keyof GetV1LibrariesResponses];

export type PostV1LibrariesData = {
    /**
     * Create library
     */
    body: HandlersLibraryCreateRequest;
    path?: never;
    query?: never;
    url: '/v1/libraries';
};

export type PostV1LibrariesErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1LibrariesError = PostV1LibrariesErrors[keyof PostV1LibrariesErrors];

export type PostV1LibrariesResponses = {
    /**
     * Created
     */
    201: HandlersLibrarySwagger;
};

export type PostV1LibrariesResponse = PostV1LibrariesResponses[keyof PostV1LibrariesResponses];

export type DeleteV1LibrariesByIdData = {
    body?: never;
    path: {
        /**
         * Library ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/libraries/{id}';
};

export type DeleteV1LibrariesByIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1LibrariesByIdResponse = DeleteV1LibrariesByIdResponses[keyof DeleteV1LibrariesByIdResponses];

export type GetV1LibrariesByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/libraries/{id}';
};

export type GetV1LibrariesByIdResponses = {
    /**
     * OK
     */
    200: HandlersLibrarySwagger;
};

export type GetV1LibrariesByIdResponse = GetV1LibrariesByIdResponses[keyof GetV1LibrariesByIdResponses];

export type PutV1LibrariesByIdData = {
    /**
     * Update library
     */
    body: HandlersLibraryUpdateRequest;
    path: {
        /**
         * Library ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/libraries/{id}';
};

export type PutV1LibrariesByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1LibrariesByIdError = PutV1LibrariesByIdErrors[keyof PutV1LibrariesByIdErrors];

export type PutV1LibrariesByIdResponses = {
    /**
     * OK
     */
    200: HandlersLibrarySwagger;
};

export type PutV1LibrariesByIdResponse = PutV1LibrariesByIdResponses[keyof PutV1LibrariesByIdResponses];

export type PostV1LibrariesByIdScanData = {
    body?: never;
    path: {
        /**
         * Library ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/libraries/{id}/scan';
};

export type PostV1LibrariesByIdScanErrors = {
    /**
     * Conflict
     */
    409: {
        [key: string]: string;
    };
};

export type PostV1LibrariesByIdScanError = PostV1LibrariesByIdScanErrors[keyof PostV1LibrariesByIdScanErrors];

export type PostV1LibrariesByIdScanResponses = {
    /**
     * Accepted
     */
    202: {
        [key: string]: string;
    };
};

export type PostV1LibrariesByIdScanResponse = PostV1LibrariesByIdScanResponses[keyof PostV1LibrariesByIdScanResponses];

export type GetV1LibraryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Items per page
         */
        pageSize?: number;
        /**
         * Filter by type (movie/series)
         */
        type?: string;
        /**
         * Search by title
         */
        search?: string;
        /**
         * Sort field (title/year/createdAt)
         */
        sortBy?: string;
        /**
         * Sort direction (asc/desc)
         */
        sortDir?: string;
    };
    url: '/v1/library';
};

export type GetV1LibraryResponses = {
    /**
     * OK
     */
    200: ModelPaginatedLibraryResponse;
};

export type GetV1LibraryResponse = GetV1LibraryResponses[keyof GetV1LibraryResponses];

export type GetV1MovieByIdData = {
    body?: never;
    path: {
        /**
         * Movie ID
         */
        id: number;
    };
    query?: never;
    url: '/v1/movie/{id}';
};

export type GetV1MovieByIdResponses = {
    /**
     * OK
     */
    200: ModelMovieDetail;
};

export type GetV1MovieByIdResponse = GetV1MovieByIdResponses[keyof GetV1MovieByIdResponses];

export type PostV1MovieByIdCandidateDownloadData = {
    /**
     * Download request
     */
    body: HandlersEnqueueCandidateRequest;
    path: {
        /**
         * Movie ID (TMDB ID)
         */
        id: number;
    };
    query?: never;
    url: '/v1/movie/{id}/candidate/download';
};

export type PostV1MovieByIdCandidateDownloadErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1MovieByIdCandidateDownloadError = PostV1MovieByIdCandidateDownloadErrors[keyof PostV1MovieByIdCandidateDownloadErrors];

export type PostV1MovieByIdCandidateDownloadResponses = {
    /**
     * OK
     */
    200: HandlersDownloadCandidateResponse;
};

export type PostV1MovieByIdCandidateDownloadResponse = PostV1MovieByIdCandidateDownloadResponses[keyof PostV1MovieByIdCandidateDownloadResponses];

export type PostV1MovieByIdCandidatePreviewData = {
    /**
     * Preview request
     */
    body: HandlersEnqueueCandidateRequest;
    path: {
        /**
         * Movie ID (TMDB ID)
         */
        id: number;
    };
    query?: never;
    url: '/v1/movie/{id}/candidate/preview';
};

export type PostV1MovieByIdCandidatePreviewErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1MovieByIdCandidatePreviewError = PostV1MovieByIdCandidatePreviewErrors[keyof PostV1MovieByIdCandidatePreviewErrors];

export type PostV1MovieByIdCandidatePreviewResponses = {
    /**
     * OK
     */
    200: ModelEvaluationTrace;
};

export type PostV1MovieByIdCandidatePreviewResponse = PostV1MovieByIdCandidatePreviewResponses[keyof PostV1MovieByIdCandidatePreviewResponses];

export type GetV1MovieByIdCandidatesData = {
    body?: never;
    path: {
        /**
         * Movie ID (TMDB ID)
         */
        id: number;
    };
    query?: never;
    url: '/v1/movie/{id}/candidates';
};

export type GetV1MovieByIdCandidatesErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetV1MovieByIdCandidatesError = GetV1MovieByIdCandidatesErrors[keyof GetV1MovieByIdCandidatesErrors];

export type GetV1MovieByIdCandidatesResponses = {
    /**
     * OK
     */
    200: Array<ModelDownloadCandidate>;
};

export type GetV1MovieByIdCandidatesResponse = GetV1MovieByIdCandidatesResponses[keyof GetV1MovieByIdCandidatesResponses];

export type GetV1MovieByIdDownloadJobsData = {
    body?: never;
    path: {
        /**
         * Movie ID (TMDB ID)
         */
        id: number;
    };
    query?: never;
    url: '/v1/movie/{id}/download-jobs';
};

export type GetV1MovieByIdDownloadJobsErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type GetV1MovieByIdDownloadJobsError = GetV1MovieByIdDownloadJobsErrors[keyof GetV1MovieByIdDownloadJobsErrors];

export type GetV1MovieByIdDownloadJobsResponses = {
    /**
     * OK
     */
    200: Array<DbgenDownloadJob>;
};

export type GetV1MovieByIdDownloadJobsResponse = GetV1MovieByIdDownloadJobsResponses[keyof GetV1MovieByIdDownloadJobsResponses];

export type GetV1NameTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/name-templates';
};

export type GetV1NameTemplatesResponses = {
    /**
     * OK
     */
    200: Array<HandlersNameTemplateSwagger>;
};

export type GetV1NameTemplatesResponse = GetV1NameTemplatesResponses[keyof GetV1NameTemplatesResponses];

export type PostV1NameTemplatesData = {
    /**
     * Create name template
     */
    body: HandlersNameTemplateCreateRequest;
    path?: never;
    query?: never;
    url: '/v1/name-templates';
};

export type PostV1NameTemplatesErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1NameTemplatesError = PostV1NameTemplatesErrors[keyof PostV1NameTemplatesErrors];

export type PostV1NameTemplatesResponses = {
    /**
     * Created
     */
    201: HandlersNameTemplateSwagger;
};

export type PostV1NameTemplatesResponse = PostV1NameTemplatesResponses[keyof PostV1NameTemplatesResponses];

export type GetV1NameTemplatesDefaultByTypeData = {
    body?: never;
    path: {
        /**
         * Template type (movie or series)
         */
        type: string;
    };
    query?: never;
    url: '/v1/name-templates/default/{type}';
};

export type GetV1NameTemplatesDefaultByTypeErrors = {
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type GetV1NameTemplatesDefaultByTypeError = GetV1NameTemplatesDefaultByTypeErrors[keyof GetV1NameTemplatesDefaultByTypeErrors];

export type GetV1NameTemplatesDefaultByTypeResponses = {
    /**
     * OK
     */
    200: HandlersNameTemplateSwagger;
};

export type GetV1NameTemplatesDefaultByTypeResponse = GetV1NameTemplatesDefaultByTypeResponses[keyof GetV1NameTemplatesDefaultByTypeResponses];

export type DeleteV1NameTemplatesByIdData = {
    body?: never;
    path: {
        /**
         * Name Template ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/name-templates/{id}';
};

export type DeleteV1NameTemplatesByIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1NameTemplatesByIdResponse = DeleteV1NameTemplatesByIdResponses[keyof DeleteV1NameTemplatesByIdResponses];

export type GetV1NameTemplatesByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/name-templates/{id}';
};

export type GetV1NameTemplatesByIdResponses = {
    /**
     * OK
     */
    200: HandlersNameTemplateSwagger;
};

export type GetV1NameTemplatesByIdResponse = GetV1NameTemplatesByIdResponses[keyof GetV1NameTemplatesByIdResponses];

export type PutV1NameTemplatesByIdData = {
    /**
     * Update name template
     */
    body: HandlersNameTemplateUpdateRequest;
    path: {
        /**
         * Name Template ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/name-templates/{id}';
};

export type PutV1NameTemplatesByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1NameTemplatesByIdError = PutV1NameTemplatesByIdErrors[keyof PutV1NameTemplatesByIdErrors];

export type PutV1NameTemplatesByIdResponses = {
    /**
     * OK
     */
    200: HandlersNameTemplateSwagger;
};

export type PutV1NameTemplatesByIdResponse = PutV1NameTemplatesByIdResponses[keyof PutV1NameTemplatesByIdResponses];

export type GetV1PersonByIdData = {
    body?: never;
    path: {
        /**
         * Person ID
         */
        id: number;
    };
    query?: never;
    url: '/v1/person/{id}';
};

export type GetV1PersonByIdResponses = {
    /**
     * OK
     */
    200: ModelPersonDetail;
};

export type GetV1PersonByIdResponse = GetV1PersonByIdResponses[keyof GetV1PersonByIdResponses];

export type GetV1PoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/policies';
};

export type GetV1PoliciesResponses = {
    /**
     * OK
     */
    200: Array<DbgenPolicy>;
};

export type GetV1PoliciesResponse = GetV1PoliciesResponses[keyof GetV1PoliciesResponses];

export type PostV1PoliciesData = {
    /**
     * Create policy
     */
    body: HandlersPolicyCreateRequest;
    path?: never;
    query?: never;
    url: '/v1/policies';
};

export type PostV1PoliciesErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1PoliciesError = PostV1PoliciesErrors[keyof PostV1PoliciesErrors];

export type PostV1PoliciesResponses = {
    /**
     * Created
     */
    201: DbgenPolicy;
};

export type PostV1PoliciesResponse = PostV1PoliciesResponses[keyof PostV1PoliciesResponses];

export type PostV1PoliciesEvaluateData = {
    /**
     * Download candidate
     */
    body: ModelDownloadCandidate;
    path?: never;
    query?: never;
    url: '/v1/policies/evaluate';
};

export type PostV1PoliciesEvaluateErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1PoliciesEvaluateError = PostV1PoliciesEvaluateErrors[keyof PostV1PoliciesEvaluateErrors];

export type PostV1PoliciesEvaluateResponses = {
    /**
     * OK
     */
    200: ModelEvaluationTrace;
};

export type PostV1PoliciesEvaluateResponse = PostV1PoliciesEvaluateResponses[keyof PostV1PoliciesEvaluateResponses];

export type GetV1PoliciesFieldsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/policies/fields';
};

export type GetV1PoliciesFieldsResponses = {
    /**
     * OK
     */
    200: Array<ModelFieldDefinition>;
};

export type GetV1PoliciesFieldsResponse = GetV1PoliciesFieldsResponses[keyof GetV1PoliciesFieldsResponses];

export type DeleteV1PoliciesByIdData = {
    body?: never;
    path: {
        /**
         * Policy ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/policies/{id}';
};

export type DeleteV1PoliciesByIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1PoliciesByIdResponse = DeleteV1PoliciesByIdResponses[keyof DeleteV1PoliciesByIdResponses];

export type GetV1PoliciesByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/policies/{id}';
};

export type GetV1PoliciesByIdResponses = {
    /**
     * OK
     */
    200: DbgenPolicy;
};

export type GetV1PoliciesByIdResponse = GetV1PoliciesByIdResponses[keyof GetV1PoliciesByIdResponses];

export type PutV1PoliciesByIdData = {
    /**
     * Update policy
     */
    body: HandlersPolicyUpdateRequest;
    path: {
        /**
         * Policy ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/policies/{id}';
};

export type PutV1PoliciesByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1PoliciesByIdError = PutV1PoliciesByIdErrors[keyof PutV1PoliciesByIdErrors];

export type PutV1PoliciesByIdResponses = {
    /**
     * OK
     */
    200: DbgenPolicy;
};

export type PutV1PoliciesByIdResponse = PutV1PoliciesByIdResponses[keyof PutV1PoliciesByIdResponses];

export type GetV1PoliciesByIdActionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/policies/{id}/actions';
};

export type GetV1PoliciesByIdActionsResponses = {
    /**
     * OK
     */
    200: Array<DbgenAction>;
};

export type GetV1PoliciesByIdActionsResponse = GetV1PoliciesByIdActionsResponses[keyof GetV1PoliciesByIdActionsResponses];

export type PostV1PoliciesByIdActionsData = {
    /**
     * Create action
     */
    body: HandlersActionCreateRequest;
    path: {
        /**
         * Policy ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/policies/{id}/actions';
};

export type PostV1PoliciesByIdActionsErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1PoliciesByIdActionsError = PostV1PoliciesByIdActionsErrors[keyof PostV1PoliciesByIdActionsErrors];

export type PostV1PoliciesByIdActionsResponses = {
    /**
     * Created
     */
    201: DbgenAction;
};

export type PostV1PoliciesByIdActionsResponse = PostV1PoliciesByIdActionsResponses[keyof PostV1PoliciesByIdActionsResponses];

export type DeleteV1PoliciesByIdActionsByActionIdData = {
    body?: never;
    path: {
        /**
         * Policy ID
         */
        id: string;
        /**
         * Action ID
         */
        actionId: string;
    };
    query?: never;
    url: '/v1/policies/{id}/actions/{actionId}';
};

export type DeleteV1PoliciesByIdActionsByActionIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1PoliciesByIdActionsByActionIdResponse = DeleteV1PoliciesByIdActionsByActionIdResponses[keyof DeleteV1PoliciesByIdActionsByActionIdResponses];

export type GetV1PoliciesByIdActionsByActionIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/policies/{id}/actions/{actionId}';
};

export type GetV1PoliciesByIdActionsByActionIdResponses = {
    /**
     * OK
     */
    200: DbgenAction;
};

export type GetV1PoliciesByIdActionsByActionIdResponse = GetV1PoliciesByIdActionsByActionIdResponses[keyof GetV1PoliciesByIdActionsByActionIdResponses];

export type PutV1PoliciesByIdActionsByActionIdData = {
    /**
     * Update action
     */
    body: HandlersActionUpdateRequest;
    path: {
        /**
         * Policy ID
         */
        id: string;
        /**
         * Action ID
         */
        actionId: string;
    };
    query?: never;
    url: '/v1/policies/{id}/actions/{actionId}';
};

export type PutV1PoliciesByIdActionsByActionIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1PoliciesByIdActionsByActionIdError = PutV1PoliciesByIdActionsByActionIdErrors[keyof PutV1PoliciesByIdActionsByActionIdErrors];

export type PutV1PoliciesByIdActionsByActionIdResponses = {
    /**
     * OK
     */
    200: DbgenAction;
};

export type PutV1PoliciesByIdActionsByActionIdResponse = PutV1PoliciesByIdActionsByActionIdResponses[keyof PutV1PoliciesByIdActionsByActionIdResponses];

export type DeleteV1PoliciesByIdRuleData = {
    body?: never;
    path: {
        /**
         * Policy ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/policies/{id}/rule';
};

export type DeleteV1PoliciesByIdRuleResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1PoliciesByIdRuleResponse = DeleteV1PoliciesByIdRuleResponses[keyof DeleteV1PoliciesByIdRuleResponses];

export type GetV1PoliciesByIdRuleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/policies/{id}/rule';
};

export type GetV1PoliciesByIdRuleResponses = {
    /**
     * OK
     */
    200: DbgenRule;
};

export type GetV1PoliciesByIdRuleResponse = GetV1PoliciesByIdRuleResponses[keyof GetV1PoliciesByIdRuleResponses];

export type PostV1PoliciesByIdRuleData = {
    /**
     * Create rule
     */
    body: HandlersRuleCreateRequest;
    path: {
        /**
         * Policy ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/policies/{id}/rule';
};

export type PostV1PoliciesByIdRuleErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1PoliciesByIdRuleError = PostV1PoliciesByIdRuleErrors[keyof PostV1PoliciesByIdRuleErrors];

export type PostV1PoliciesByIdRuleResponses = {
    /**
     * Created
     */
    201: DbgenRule;
};

export type PostV1PoliciesByIdRuleResponse = PostV1PoliciesByIdRuleResponses[keyof PostV1PoliciesByIdRuleResponses];

export type PutV1PoliciesByIdRuleData = {
    /**
     * Update rule
     */
    body: HandlersRuleUpdateRequest;
    path: {
        /**
         * Policy ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/policies/{id}/rule';
};

export type PutV1PoliciesByIdRuleErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1PoliciesByIdRuleError = PutV1PoliciesByIdRuleErrors[keyof PutV1PoliciesByIdRuleErrors];

export type PutV1PoliciesByIdRuleResponses = {
    /**
     * OK
     */
    200: DbgenRule;
};

export type PutV1PoliciesByIdRuleResponse = PutV1PoliciesByIdRuleResponses[keyof PutV1PoliciesByIdRuleResponses];

export type GetV1RolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/roles';
};

export type GetV1RolesResponses = {
    /**
     * OK
     */
    200: Array<DbgenRole>;
};

export type GetV1RolesResponse = GetV1RolesResponses[keyof GetV1RolesResponses];

export type GetV1SearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search query
         */
        q: string;
        /**
         * Max results (default 20)
         */
        limit?: number;
        /**
         * Page number (default 1)
         */
        page?: number;
    };
    url: '/v1/search';
};

export type GetV1SearchResponses = {
    /**
     * OK
     */
    200: ModelSearchResponse;
};

export type GetV1SearchResponse = GetV1SearchResponses[keyof GetV1SearchResponses];

export type GetV1SeriesByIdData = {
    body?: never;
    path: {
        /**
         * Series ID
         */
        id: number;
    };
    query?: never;
    url: '/v1/series/{id}';
};

export type GetV1SeriesByIdResponses = {
    /**
     * OK
     */
    200: ModelSeriesDetail;
};

export type GetV1SeriesByIdResponse = GetV1SeriesByIdResponses[keyof GetV1SeriesByIdResponses];

export type PostV1SeriesByIdCandidateDownloadData = {
    /**
     * Download request
     */
    body: HandlersEnqueueCandidateRequest;
    path: {
        /**
         * Series ID (TMDB ID)
         */
        id: number;
    };
    query?: never;
    url: '/v1/series/{id}/candidate/download';
};

export type PostV1SeriesByIdCandidateDownloadErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1SeriesByIdCandidateDownloadError = PostV1SeriesByIdCandidateDownloadErrors[keyof PostV1SeriesByIdCandidateDownloadErrors];

export type PostV1SeriesByIdCandidateDownloadResponses = {
    /**
     * OK
     */
    200: HandlersDownloadCandidateResponse;
};

export type PostV1SeriesByIdCandidateDownloadResponse = PostV1SeriesByIdCandidateDownloadResponses[keyof PostV1SeriesByIdCandidateDownloadResponses];

export type PostV1SeriesByIdCandidatePreviewData = {
    /**
     * Preview request
     */
    body: HandlersEnqueueCandidateRequest;
    path: {
        /**
         * Series ID (TMDB ID)
         */
        id: number;
    };
    query?: never;
    url: '/v1/series/{id}/candidate/preview';
};

export type PostV1SeriesByIdCandidatePreviewErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1SeriesByIdCandidatePreviewError = PostV1SeriesByIdCandidatePreviewErrors[keyof PostV1SeriesByIdCandidatePreviewErrors];

export type PostV1SeriesByIdCandidatePreviewResponses = {
    /**
     * OK
     */
    200: ModelEvaluationTrace;
};

export type PostV1SeriesByIdCandidatePreviewResponse = PostV1SeriesByIdCandidatePreviewResponses[keyof PostV1SeriesByIdCandidatePreviewResponses];

export type GetV1SeriesByIdCandidatesData = {
    body?: never;
    path: {
        /**
         * Series ID (TMDB ID)
         */
        id: number;
    };
    query?: {
        /**
         * Season number
         */
        season?: number;
        /**
         * Episode number
         */
        episode?: number;
    };
    url: '/v1/series/{id}/candidates';
};

export type GetV1SeriesByIdCandidatesErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetV1SeriesByIdCandidatesError = GetV1SeriesByIdCandidatesErrors[keyof GetV1SeriesByIdCandidatesErrors];

export type GetV1SeriesByIdCandidatesResponses = {
    /**
     * OK
     */
    200: Array<ModelDownloadCandidate>;
};

export type GetV1SeriesByIdCandidatesResponse = GetV1SeriesByIdCandidatesResponses[keyof GetV1SeriesByIdCandidatesResponses];

export type GetV1SeriesByIdDownloadJobsData = {
    body?: never;
    path: {
        /**
         * Series ID (TMDB ID)
         */
        id: number;
    };
    query?: never;
    url: '/v1/series/{id}/download-jobs';
};

export type GetV1SeriesByIdDownloadJobsErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type GetV1SeriesByIdDownloadJobsError = GetV1SeriesByIdDownloadJobsErrors[keyof GetV1SeriesByIdDownloadJobsErrors];

export type GetV1SeriesByIdDownloadJobsResponses = {
    /**
     * OK
     */
    200: Array<DbgenListDownloadJobsByTmdbSeriesIdRow>;
};

export type GetV1SeriesByIdDownloadJobsResponse = GetV1SeriesByIdDownloadJobsResponses[keyof GetV1SeriesByIdDownloadJobsResponses];

export type GetV1SettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/settings';
};

export type GetV1SettingsResponses = {
    /**
     * OK
     */
    200: HandlersSettingsListResponse;
};

export type GetV1SettingsResponse = GetV1SettingsResponses[keyof GetV1SettingsResponses];

export type PatchV1SettingsData = {
    /**
     * Patch request
     */
    body: HandlersPatchRequest;
    path?: never;
    query?: never;
    url: '/v1/settings';
};

export type PatchV1SettingsErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PatchV1SettingsError = PatchV1SettingsErrors[keyof PatchV1SettingsErrors];

export type PatchV1SettingsResponses = {
    /**
     * No Content
     */
    204: string;
};

export type PatchV1SettingsResponse = PatchV1SettingsResponses[keyof PatchV1SettingsResponses];

export type PostV1SetupInitializeData = {
    /**
     * Setup request
     */
    body: HandlersSetupInitializeRequest;
    path?: never;
    query?: never;
    url: '/v1/setup/initialize';
};

export type PostV1SetupInitializeErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Already initialized
     */
    409: {
        [key: string]: string;
    };
};

export type PostV1SetupInitializeError = PostV1SetupInitializeErrors[keyof PostV1SetupInitializeErrors];

export type PostV1SetupInitializeResponses = {
    /**
     * OK
     */
    200: HandlersSetupInitializeResponse;
};

export type PostV1SetupInitializeResponse = PostV1SetupInitializeResponses[keyof PostV1SetupInitializeResponses];

export type GetV1SetupStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/setup/status';
};

export type GetV1SetupStatusResponses = {
    /**
     * OK
     */
    200: HandlersSetupStatusResponse;
};

export type GetV1SetupStatusResponse = GetV1SetupStatusResponses[keyof GetV1SetupStatusResponses];

export type GetV1UnmatchedFilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by library ID
         */
        libraryId?: string;
        /**
         * Page number (default 1)
         */
        page?: number;
        /**
         * Page size (default 20)
         */
        pageSize?: number;
    };
    url: '/v1/unmatched-files';
};

export type GetV1UnmatchedFilesResponses = {
    /**
     * OK
     */
    200: HandlersUnmatchedFilesListResponse;
};

export type GetV1UnmatchedFilesResponse = GetV1UnmatchedFilesResponses[keyof GetV1UnmatchedFilesResponses];

export type GetV1UnmatchedFilesByIdData = {
    body?: never;
    path: {
        /**
         * Unmatched file ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/unmatched-files/{id}';
};

export type GetV1UnmatchedFilesByIdErrors = {
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type GetV1UnmatchedFilesByIdError = GetV1UnmatchedFilesByIdErrors[keyof GetV1UnmatchedFilesByIdErrors];

export type GetV1UnmatchedFilesByIdResponses = {
    /**
     * OK
     */
    200: HandlersUnmatchedFileSwagger;
};

export type GetV1UnmatchedFilesByIdResponse = GetV1UnmatchedFilesByIdResponses[keyof GetV1UnmatchedFilesByIdResponses];

export type PostV1UnmatchedFilesByIdDismissData = {
    body?: never;
    path: {
        /**
         * Unmatched file ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/unmatched-files/{id}/dismiss';
};

export type PostV1UnmatchedFilesByIdDismissErrors = {
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type PostV1UnmatchedFilesByIdDismissError = PostV1UnmatchedFilesByIdDismissErrors[keyof PostV1UnmatchedFilesByIdDismissErrors];

export type PostV1UnmatchedFilesByIdDismissResponses = {
    /**
     * No Content
     */
    204: string;
};

export type PostV1UnmatchedFilesByIdDismissResponse = PostV1UnmatchedFilesByIdDismissResponses[keyof PostV1UnmatchedFilesByIdDismissResponses];

export type PostV1UnmatchedFilesByIdMatchData = {
    /**
     * Match request
     */
    body: HandlersUnmatchedFileMatchRequest;
    path: {
        /**
         * Unmatched file ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/unmatched-files/{id}/match';
};

export type PostV1UnmatchedFilesByIdMatchErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type PostV1UnmatchedFilesByIdMatchError = PostV1UnmatchedFilesByIdMatchErrors[keyof PostV1UnmatchedFilesByIdMatchErrors];

export type PostV1UnmatchedFilesByIdMatchResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostV1UnmatchedFilesByIdMatchResponse = PostV1UnmatchedFilesByIdMatchResponses[keyof PostV1UnmatchedFilesByIdMatchResponses];

export type PostV1UnmatchedFilesByIdRefreshData = {
    body?: never;
    path: {
        /**
         * Unmatched file ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/unmatched-files/{id}/refresh';
};

export type PostV1UnmatchedFilesByIdRefreshErrors = {
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type PostV1UnmatchedFilesByIdRefreshError = PostV1UnmatchedFilesByIdRefreshErrors[keyof PostV1UnmatchedFilesByIdRefreshErrors];

export type PostV1UnmatchedFilesByIdRefreshResponses = {
    /**
     * OK
     */
    200: HandlersUnmatchedFileSwagger;
};

export type PostV1UnmatchedFilesByIdRefreshResponse = PostV1UnmatchedFilesByIdRefreshResponses[keyof PostV1UnmatchedFilesByIdRefreshResponses];

export type GetV1UsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/users';
};

export type GetV1UsersResponses = {
    /**
     * OK
     */
    200: Array<HandlersUserSwagger>;
};

export type GetV1UsersResponse = GetV1UsersResponses[keyof GetV1UsersResponses];

export type DeleteV1UsersByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/users/{id}';
};

export type DeleteV1UsersByIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1UsersByIdResponse = DeleteV1UsersByIdResponses[keyof DeleteV1UsersByIdResponses];

export type GetV1UsersByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/users/{id}';
};

export type GetV1UsersByIdResponses = {
    /**
     * OK
     */
    200: HandlersUserSwagger;
};

export type GetV1UsersByIdResponse = GetV1UsersByIdResponses[keyof GetV1UsersByIdResponses];

export type PutV1UsersByIdData = {
    /**
     * Update user
     */
    body: HandlersUserUpdateRequest;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/users/{id}';
};

export type PutV1UsersByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1UsersByIdError = PutV1UsersByIdErrors[keyof PutV1UsersByIdErrors];

export type PutV1UsersByIdResponses = {
    /**
     * OK
     */
    200: HandlersUserSwagger;
};

export type PutV1UsersByIdResponse = PutV1UsersByIdResponses[keyof PutV1UsersByIdResponses];

export type PutV1UsersByIdPasswordData = {
    /**
     * Update password
     */
    body: HandlersUserPasswordUpdateRequest;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/users/{id}/password';
};

export type PutV1UsersByIdPasswordResponses = {
    /**
     * No Content
     */
    204: string;
};

export type PutV1UsersByIdPasswordResponse = PutV1UsersByIdPasswordResponses[keyof PutV1UsersByIdPasswordResponses];

export type PutV1UsersByIdRoleData = {
    /**
     * Assign role
     */
    body: HandlersUserRoleUpdateRequest;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/users/{id}/role';
};

export type PutV1UsersByIdRoleResponses = {
    /**
     * No Content
     */
    204: string;
};

export type PutV1UsersByIdRoleResponse = PutV1UsersByIdRoleResponses[keyof PutV1UsersByIdRoleResponses];

export type GetV1VersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/version';
};

export type GetV1VersionResponses = {
    /**
     * OK
     */
    200: ServiceVersionInfo;
};

export type GetV1VersionResponse = GetV1VersionResponses[keyof GetV1VersionResponses];
