// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type DbgenAction = {
    created_at: string;
    id: string;
    order: number;
    policy_id: string;
    type: string;
    updated_at: string;
    value: string;
};

export type DbgenDownloader = {
    config_json: Array<number>;
    created_at: string;
    default: boolean;
    enabled: boolean;
    id: string;
    name: string;
    password: string;
    protocol: string;
    type: string;
    updated_at: string;
    url: string;
    username: string;
};

export type DbgenMediaItem = {
    created_at: string;
    id: string;
    library_id: string;
    title: string;
    tmdb_id: number;
    type: string;
    updated_at: string;
    year: number;
};

export type DbgenPolicy = {
    created_at: string;
    description: string;
    enabled: boolean;
    id: string;
    name: string;
    priority: number;
    updated_at: string;
};

export type DbgenRule = {
    created_at: string;
    id: string;
    left_operand: string;
    operator: string;
    policy_id: string;
    right_operand: string;
    updated_at: string;
};

export type HandlersActionCreateRequest = {
    order: number;
    type: string;
    value: string;
};

export type HandlersActionUpdateRequest = {
    order: number;
    type: string;
    value: string;
};

export type HandlersDownloaderCreateRequest = {
    config_json: {
        [key: string]: unknown;
    };
    default: boolean;
    enabled: boolean;
    name: string;
    password: string;
    protocol: string;
    type: string;
    url: string;
    username: string;
};

export type HandlersDownloaderUpdateRequest = {
    config_json: {
        [key: string]: unknown;
    };
    default: boolean;
    enabled: boolean;
    name: string;
    password: string;
    protocol: string;
    type: string;
    url: string;
    username: string;
};

export type HandlersEnqueueCandidateRequest = {
    guid: string;
    indexerId: number;
};

export type HandlersLibraryCreateRequest = {
    default: boolean;
    enabled: boolean;
    name: string;
    root_path: string;
    type: string;
};

export type HandlersLibraryUpdateRequest = {
    default: boolean;
    enabled: boolean;
    name: string;
    root_path: string;
    type: string;
};

export type HandlersLoginRequest = {
    email: string;
    password: string;
};

export type HandlersLoginResponse = {
    token: string;
};

export type HandlersNameTemplateCreateRequest = {
    default: boolean;
    name: string;
    template: string;
    type: string;
};

export type HandlersNameTemplateUpdateRequest = {
    default: boolean;
    name: string;
    template: string;
    type: string;
};

export type HandlersPatchRequest = {
    key: string;
    value: unknown;
};

export type HandlersPolicyCreateRequest = {
    description: string;
    enabled: boolean;
    name: string;
    priority: number;
};

export type HandlersPolicyUpdateRequest = {
    description: string;
    enabled: boolean;
    name: string;
    priority: number;
};

export type HandlersRuleCreateRequest = {
    left_operand: string;
    operator: string;
    right_operand: string;
};

export type HandlersRuleUpdateRequest = {
    left_operand: string;
    operator: string;
    right_operand: string;
};

export type HandlersSettingsListResponse = {
    [key: string]: unknown;
};

export type HandlersLibrarySwagger = {
    created_at: string;
    default: boolean;
    enabled: boolean;
    id: string;
    name: string;
    root_path: string;
    type: string;
    updated_at: string;
};

export type HandlersNameTemplateSwagger = {
    created_at: string;
    default: boolean;
    id: string;
    name: string;
    template: string;
    type: string;
    updated_at: string;
};

export type ModelActionInfo = {
    order: number;
    type: string;
    value: string;
};

export type ModelCapabilities = {
    bookSearchParams: Array<string>;
    categories: Array<ModelCategories>;
    limitsDefault: number;
    limitsMax: number;
    movieSearchParams: Array<string>;
    musicSearchParams: Array<string>;
    searchParams: Array<string>;
    supportsRawSearch: boolean;
    tvSearchParams: Array<string>;
};

export type ModelCategories = {
    id: number;
    name: string;
    subCategories: Array<ModelCategories>;
};

export type ModelDownloadCandidate = {
    /**
     * age in seconds
     */
    age: number;
    ageHours: number;
    categories: Array<string>;
    filename: string;
    grabs: number;
    guid: string;
    indexer: string;
    indexerId: number;
    link: string;
    /**
     * leechers
     */
    peers: number;
    protocol: string;
    publishDate: string;
    /**
     * seeders
     */
    seeders: number;
    /**
     * size in bytes
     */
    size: number;
    title: string;
};

export type ModelEnumValue = {
    label: string;
    value: string;
};

export type ModelEvaluationTrace = {
    finalPlan: ModelPlan;
    policies: Array<ModelPolicyEvaluation>;
};

export type ModelFieldDefinition = {
    /**
     * API endpoint for dynamic fields
     */
    dynamicSource?: string;
    /**
     * For enum type
     */
    enumValues?: Array<ModelEnumValue>;
    /**
     * Display name
     */
    label: string;
    /**
     * Valid operators for this field
     */
    operators: Array<string>;
    /**
     * e.g., "candidate.size", "quality.resolution"
     */
    path: string;
    /**
     * "text", "number", "enum", "dynamic", "boolean"
     */
    type: ModelFieldType;
    /**
     * "string", "int64", "float64", "[]string", "bool"
     */
    valueType: string;
};

export type ModelFieldInput = {
    name: string;
    value?: unknown;
};

export type ModelFieldOutput = {
    advanced?: boolean;
    helpLink?: string;
    helpText?: string;
    hidden?: string;
    label?: string;
    name: string;
    order?: number;
    privacy: string;
    selectOptions?: Array<ModelSelectOption>;
    selectOptionsProviderAction?: string;
    type?: string;
    value?: unknown;
};

export type ModelFieldType = 'text' | 'number' | 'enum' | 'dynamic' | 'boolean';

export type ModelGenre = {
    name: string;
    tmdbId: number;
};

export type ModelIndexerCapabilities = {
    bookSearchParams: Array<string>;
    categories: Array<ModelIndexerCategory>;
    limitsDefault: number;
    limitsMax: number;
    movieSearchParams: Array<string>;
    musicSearchParams: Array<string>;
    searchParams: Array<string>;
    supportsRawSearch: boolean;
    tvSearchParams: Array<string>;
};

export type ModelIndexerCategory = {
    id: number;
    name: string;
    subCategories: Array<ModelIndexerCategory>;
};

export type ModelIndexerDefinition = {
    added: string;
    appProfileId: number;
    capabilities: ModelIndexerCapabilities;
    configContract: string;
    definitionName: string;
    description: string;
    downloadClientId: number;
    enable: boolean;
    encoding: string;
    fields: Array<ModelIndexerField>;
    implementation: string;
    implementationName: string;
    indexerUrls: Array<string>;
    infoLink: string;
    language: string;
    legacyUrls: Array<string>;
    name: string;
    presets: Array<unknown>;
    priority: number;
    privacy: string;
    protocol: string;
    redirect: boolean;
    sortName: string;
    supportsPagination: boolean;
    supportsRedirect: boolean;
    supportsRss: boolean;
    supportsSearch: boolean;
    tags: Array<string>;
};

export type ModelIndexerField = {
    advanced: boolean;
    helpLink?: string;
    helpText?: string;
    helpTextWarning?: string;
    hidden?: string;
    isFloat: boolean;
    label: string;
    name: string;
    order: number;
    privacy: string;
    selectOptions?: Array<ModelIndexerSelectOption>;
    selectOptionsProviderAction?: string;
    type: string;
    unit?: string;
    value?: unknown;
};

export type ModelIndexerInput = {
    appProfileId: number;
    configContract: string;
    enable: boolean;
    fields: Array<ModelFieldInput>;
    id?: number;
    implementation: string;
    name: string;
    priority: number;
    protocol: ModelProtocol;
    redirect: boolean;
    tags?: Array<number>;
};

export type ModelIndexerOutput = {
    added: string;
    appProfileId: number;
    capabilities?: ModelCapabilities;
    configContract: string;
    definitionName: string;
    description: string;
    enable: boolean;
    encoding?: string;
    fields: Array<ModelFieldOutput>;
    id?: number;
    implementation: string;
    implementationName: string;
    indexerUrls: Array<string>;
    infoLink: string;
    language: string;
    legacyUrls: Array<string>;
    name: string;
    priority: number;
    privacy: string;
    protocol: ModelProtocol;
    redirect: boolean;
    sortName: string;
    supportsRedirect: boolean;
    supportsRss: boolean;
    supportsSearch: boolean;
    tags: Array<number>;
};

export type ModelIndexerSelectOption = {
    hint?: string;
    name: string;
    order: number;
    value: unknown;
};

export type ModelMovie = {
    backdropPath: string;
    originCountry: Array<string>;
    originalLanguage: string;
    overview: string;
    posterPath: string;
    productionCompanies: Array<ModelProductionCompany>;
    productionCountries: Array<ModelProductionCountry>;
    releaseDate: string;
    runtime: number;
    /**
     * Stats
     */
    status: string;
    tagline: string;
    title: string;
    tmdbId: number;
};

export type ModelMovieRail = {
    overview: string;
    posterPath: string;
    releaseDate: string;
    title: string;
    tmdbId: number;
};

export type ModelNetwork = {
    logoPath: string;
    name: string;
    tmdbId: number;
};

export type ModelPerson = {
    name: string;
    profilePath: string;
    tmdbId: number;
};

export type ModelPlan = {
    /**
     * how to download
     */
    downloaderId: string;
    /**
     * where to move/hardlink/copy the file to
     */
    libraryId: string;
    /**
     * how to name the file
     */
    nameTemplateId: string;
};

export type ModelPolicyEvaluation = {
    actionsApplied: Array<ModelActionInfo>;
    matched: boolean;
    policyId: string;
    policyName: string;
    priority: number;
    ruleEvaluated?: ModelRuleInfo;
    stoppedProcessing: boolean;
};

export type ModelProductionCompany = {
    logoPath: string;
    name: string;
    originCountry: string;
    tmdbId: number;
};

export type ModelProductionCountry = {
    iso3166_1: string;
    name: string;
};

export type ModelProtocol = 'unknown' | 'usenet' | 'torrent';

export type ModelRail = {
    id: string;
    movies: Array<ModelMovieRail>;
    series: Array<ModelSeriesRail>;
    title: string;
    type: string;
};

export type ModelRuleInfo = {
    leftOperand: string;
    operator: string;
    rightOperand: string;
};

export type ModelSeason = {
    airDate: string;
    overview: string;
    posterPath: string;
    seasonNumber: number;
    title: string;
    tmdbId: number;
};

export type ModelSelectOption = {
    dividerAfter?: boolean;
    hint: string;
    name: string;
    order: number;
    value: number;
};

export type ModelSeries = {
    backdropPath: string;
    createdBy: Array<ModelPerson>;
    firstAirDate: string;
    genres: Array<ModelGenre>;
    inProduction: boolean;
    lastAirDate: string;
    networks: Array<ModelNetwork>;
    overview: string;
    posterPath: string;
    seasons: Array<ModelSeason>;
    status: string;
    tagline: string;
    title: string;
    tmdbId: number;
};

export type ModelSeriesRail = {
    overview: string;
    posterPath: string;
    releaseDate: string;
    title: string;
    tmdbId: number;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * ok
     */
    200: string;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type PostV1AuthLoginData = {
    /**
     * Login request
     */
    body: HandlersLoginRequest;
    path?: never;
    query?: never;
    url: '/v1/auth/login';
};

export type PostV1AuthLoginResponses = {
    /**
     * OK
     */
    200: HandlersLoginResponse;
};

export type PostV1AuthLoginResponse = PostV1AuthLoginResponses[keyof PostV1AuthLoginResponses];

export type GetV1DownloadersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/downloaders';
};

export type GetV1DownloadersResponses = {
    /**
     * OK
     */
    200: Array<DbgenDownloader>;
};

export type GetV1DownloadersResponse = GetV1DownloadersResponses[keyof GetV1DownloadersResponses];

export type PostV1DownloadersData = {
    /**
     * Create downloader
     */
    body: HandlersDownloaderCreateRequest;
    path?: never;
    query?: never;
    url: '/v1/downloaders';
};

export type PostV1DownloadersErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1DownloadersError = PostV1DownloadersErrors[keyof PostV1DownloadersErrors];

export type PostV1DownloadersResponses = {
    /**
     * Created
     */
    201: DbgenDownloader;
};

export type PostV1DownloadersResponse = PostV1DownloadersResponses[keyof PostV1DownloadersResponses];

export type GetV1DownloadersDefaultByProtocolData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/downloaders/default/{protocol}';
};

export type GetV1DownloadersDefaultByProtocolResponses = {
    /**
     * OK
     */
    200: DbgenDownloader;
};

export type GetV1DownloadersDefaultByProtocolResponse = GetV1DownloadersDefaultByProtocolResponses[keyof GetV1DownloadersDefaultByProtocolResponses];

export type DeleteV1DownloadersByIdData = {
    body?: never;
    path: {
        /**
         * Downloader ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/downloaders/{id}';
};

export type DeleteV1DownloadersByIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1DownloadersByIdResponse = DeleteV1DownloadersByIdResponses[keyof DeleteV1DownloadersByIdResponses];

export type GetV1DownloadersByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/downloaders/{id}';
};

export type GetV1DownloadersByIdResponses = {
    /**
     * OK
     */
    200: DbgenDownloader;
};

export type GetV1DownloadersByIdResponse = GetV1DownloadersByIdResponses[keyof GetV1DownloadersByIdResponses];

export type PutV1DownloadersByIdData = {
    /**
     * Update downloader
     */
    body: HandlersDownloaderUpdateRequest;
    path: {
        /**
         * Downloader ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/downloaders/{id}';
};

export type PutV1DownloadersByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1DownloadersByIdError = PutV1DownloadersByIdErrors[keyof PutV1DownloadersByIdErrors];

export type PutV1DownloadersByIdResponses = {
    /**
     * OK
     */
    200: DbgenDownloader;
};

export type PutV1DownloadersByIdResponse = PutV1DownloadersByIdResponses[keyof PutV1DownloadersByIdResponses];

export type PostV1DownloadersByIdTestData = {
    body?: never;
    path: {
        /**
         * Downloader ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/downloaders/{id}/test';
};

export type PostV1DownloadersByIdTestErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1DownloadersByIdTestError = PostV1DownloadersByIdTestErrors[keyof PostV1DownloadersByIdTestErrors];

export type PostV1DownloadersByIdTestResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostV1DownloadersByIdTestResponse = PostV1DownloadersByIdTestResponses[keyof PostV1DownloadersByIdTestResponses];

export type GetV1HomeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/home';
};

export type GetV1HomeResponses = {
    /**
     * OK
     */
    200: Array<ModelRail>;
};

export type GetV1HomeResponse = GetV1HomeResponses[keyof GetV1HomeResponses];

export type PostV1IndexerData = {
    /**
     * Save indexer
     */
    body: ModelIndexerInput;
    path?: never;
    query?: never;
    url: '/v1/indexer';
};

export type PostV1IndexerErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1IndexerError = PostV1IndexerErrors[keyof PostV1IndexerErrors];

export type PostV1IndexerResponses = {
    /**
     * OK
     */
    200: ModelIndexerOutput;
};

export type PostV1IndexerResponse = PostV1IndexerResponses[keyof PostV1IndexerResponses];

export type PostV1IndexerActionByNameData = {
    body?: never;
    path: {
        /**
         * Action name
         */
        name: string;
    };
    query?: never;
    url: '/v1/indexer/action/{name}';
};

export type PostV1IndexerActionByNameErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1IndexerActionByNameError = PostV1IndexerActionByNameErrors[keyof PostV1IndexerActionByNameErrors];

export type PostV1IndexerActionByNameResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetV1IndexersConfiguredData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/indexers/configured';
};

export type GetV1IndexersConfiguredResponses = {
    /**
     * OK
     */
    200: Array<ModelIndexerOutput>;
};

export type GetV1IndexersConfiguredResponse = GetV1IndexersConfiguredResponses[keyof GetV1IndexersConfiguredResponses];

export type GetV1IndexersSchemaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/indexers/schema';
};

export type GetV1IndexersSchemaResponses = {
    /**
     * OK
     */
    200: Array<Array<ModelIndexerDefinition>>;
};

export type GetV1IndexersSchemaResponse = GetV1IndexersSchemaResponses[keyof GetV1IndexersSchemaResponses];

export type DeleteV1IndexersByIdData = {
    body?: never;
    path: {
        /**
         * Indexer ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/indexers/{id}';
};

export type DeleteV1IndexersByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type DeleteV1IndexersByIdError = DeleteV1IndexersByIdErrors[keyof DeleteV1IndexersByIdErrors];

export type DeleteV1IndexersByIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1IndexersByIdResponse = DeleteV1IndexersByIdResponses[keyof DeleteV1IndexersByIdResponses];

export type GetV1IndexersByIdData = {
    body?: never;
    path: {
        /**
         * Indexer ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/indexers/{id}';
};

export type GetV1IndexersByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetV1IndexersByIdError = GetV1IndexersByIdErrors[keyof GetV1IndexersByIdErrors];

export type GetV1IndexersByIdResponses = {
    /**
     * OK
     */
    200: ModelIndexerOutput;
};

export type GetV1IndexersByIdResponse = GetV1IndexersByIdResponses[keyof GetV1IndexersByIdResponses];

export type GetV1LibrariesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/libraries';
};

export type GetV1LibrariesResponses = {
    /**
     * OK
     */
    200: Array<HandlersLibrarySwagger>;
};

export type GetV1LibrariesResponse = GetV1LibrariesResponses[keyof GetV1LibrariesResponses];

export type PostV1LibrariesData = {
    /**
     * Create library
     */
    body: HandlersLibraryCreateRequest;
    path?: never;
    query?: never;
    url: '/v1/libraries';
};

export type PostV1LibrariesErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1LibrariesError = PostV1LibrariesErrors[keyof PostV1LibrariesErrors];

export type PostV1LibrariesResponses = {
    /**
     * Created
     */
    201: HandlersLibrarySwagger;
};

export type PostV1LibrariesResponse = PostV1LibrariesResponses[keyof PostV1LibrariesResponses];

export type DeleteV1LibrariesByIdData = {
    body?: never;
    path: {
        /**
         * Library ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/libraries/{id}';
};

export type DeleteV1LibrariesByIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1LibrariesByIdResponse = DeleteV1LibrariesByIdResponses[keyof DeleteV1LibrariesByIdResponses];

export type GetV1LibrariesByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/libraries/{id}';
};

export type GetV1LibrariesByIdResponses = {
    /**
     * OK
     */
    200: HandlersLibrarySwagger;
};

export type GetV1LibrariesByIdResponse = GetV1LibrariesByIdResponses[keyof GetV1LibrariesByIdResponses];

export type PutV1LibrariesByIdData = {
    /**
     * Update library
     */
    body: HandlersLibraryUpdateRequest;
    path: {
        /**
         * Library ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/libraries/{id}';
};

export type PutV1LibrariesByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1LibrariesByIdError = PutV1LibrariesByIdErrors[keyof PutV1LibrariesByIdErrors];

export type PutV1LibrariesByIdResponses = {
    /**
     * OK
     */
    200: HandlersLibrarySwagger;
};

export type PutV1LibrariesByIdResponse = PutV1LibrariesByIdResponses[keyof PutV1LibrariesByIdResponses];

export type PostV1LibrariesByIdScanData = {
    body?: never;
    path: {
        /**
         * Library ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/libraries/{id}/scan';
};

export type PostV1LibrariesByIdScanResponses = {
    /**
     * No Content
     */
    204: string;
};

export type PostV1LibrariesByIdScanResponse = PostV1LibrariesByIdScanResponses[keyof PostV1LibrariesByIdScanResponses];

export type GetV1LibraryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/library';
};

export type GetV1LibraryResponses = {
    /**
     * OK
     */
    200: Array<DbgenMediaItem>;
};

export type GetV1LibraryResponse = GetV1LibraryResponses[keyof GetV1LibraryResponses];

export type GetV1MovieByIdData = {
    body?: never;
    path: {
        /**
         * Movie ID
         */
        id: number;
    };
    query?: never;
    url: '/v1/movie/{id}';
};

export type GetV1MovieByIdResponses = {
    /**
     * OK
     */
    200: ModelMovie;
};

export type GetV1MovieByIdResponse = GetV1MovieByIdResponses[keyof GetV1MovieByIdResponses];

export type PostV1MovieByIdCandidatePreviewData = {
    /**
     * Preview request
     */
    body: HandlersEnqueueCandidateRequest;
    path: {
        /**
         * Movie ID (TMDB ID)
         */
        id: number;
    };
    query?: never;
    url: '/v1/movie/{id}/candidate/preview';
};

export type PostV1MovieByIdCandidatePreviewErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1MovieByIdCandidatePreviewError = PostV1MovieByIdCandidatePreviewErrors[keyof PostV1MovieByIdCandidatePreviewErrors];

export type PostV1MovieByIdCandidatePreviewResponses = {
    /**
     * OK
     */
    200: ModelEvaluationTrace;
};

export type PostV1MovieByIdCandidatePreviewResponse = PostV1MovieByIdCandidatePreviewResponses[keyof PostV1MovieByIdCandidatePreviewResponses];

export type GetV1MovieByIdCandidatesData = {
    body?: never;
    path: {
        /**
         * Movie ID (TMDB ID)
         */
        id: number;
    };
    query?: never;
    url: '/v1/movie/{id}/candidates';
};

export type GetV1MovieByIdCandidatesErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type GetV1MovieByIdCandidatesError = GetV1MovieByIdCandidatesErrors[keyof GetV1MovieByIdCandidatesErrors];

export type GetV1MovieByIdCandidatesResponses = {
    /**
     * OK
     */
    200: Array<ModelDownloadCandidate>;
};

export type GetV1MovieByIdCandidatesResponse = GetV1MovieByIdCandidatesResponses[keyof GetV1MovieByIdCandidatesResponses];

export type PostV1MovieByIdEnqueueCandidateData = {
    /**
     * Enqueue request
     */
    body: HandlersEnqueueCandidateRequest;
    path: {
        /**
         * Movie ID (TMDB ID)
         */
        id: number;
    };
    query?: never;
    url: '/v1/movie/{id}/enqueue-candidate';
};

export type PostV1MovieByIdEnqueueCandidateErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
    /**
     * Internal Server Error
     */
    500: {
        [key: string]: string;
    };
};

export type PostV1MovieByIdEnqueueCandidateError = PostV1MovieByIdEnqueueCandidateErrors[keyof PostV1MovieByIdEnqueueCandidateErrors];

export type PostV1MovieByIdEnqueueCandidateResponses = {
    /**
     * OK
     */
    200: ModelEvaluationTrace;
};

export type PostV1MovieByIdEnqueueCandidateResponse = PostV1MovieByIdEnqueueCandidateResponses[keyof PostV1MovieByIdEnqueueCandidateResponses];

export type GetV1NameTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/name-templates';
};

export type GetV1NameTemplatesResponses = {
    /**
     * OK
     */
    200: Array<HandlersNameTemplateSwagger>;
};

export type GetV1NameTemplatesResponse = GetV1NameTemplatesResponses[keyof GetV1NameTemplatesResponses];

export type PostV1NameTemplatesData = {
    /**
     * Create name template
     */
    body: HandlersNameTemplateCreateRequest;
    path?: never;
    query?: never;
    url: '/v1/name-templates';
};

export type PostV1NameTemplatesErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1NameTemplatesError = PostV1NameTemplatesErrors[keyof PostV1NameTemplatesErrors];

export type PostV1NameTemplatesResponses = {
    /**
     * Created
     */
    201: HandlersNameTemplateSwagger;
};

export type PostV1NameTemplatesResponse = PostV1NameTemplatesResponses[keyof PostV1NameTemplatesResponses];

export type GetV1NameTemplatesDefaultByTypeData = {
    body?: never;
    path: {
        /**
         * Template type (movie or series)
         */
        type: string;
    };
    query?: never;
    url: '/v1/name-templates/default/{type}';
};

export type GetV1NameTemplatesDefaultByTypeErrors = {
    /**
     * Not Found
     */
    404: {
        [key: string]: string;
    };
};

export type GetV1NameTemplatesDefaultByTypeError = GetV1NameTemplatesDefaultByTypeErrors[keyof GetV1NameTemplatesDefaultByTypeErrors];

export type GetV1NameTemplatesDefaultByTypeResponses = {
    /**
     * OK
     */
    200: HandlersNameTemplateSwagger;
};

export type GetV1NameTemplatesDefaultByTypeResponse = GetV1NameTemplatesDefaultByTypeResponses[keyof GetV1NameTemplatesDefaultByTypeResponses];

export type DeleteV1NameTemplatesByIdData = {
    body?: never;
    path: {
        /**
         * Name Template ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/name-templates/{id}';
};

export type DeleteV1NameTemplatesByIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1NameTemplatesByIdResponse = DeleteV1NameTemplatesByIdResponses[keyof DeleteV1NameTemplatesByIdResponses];

export type GetV1NameTemplatesByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/name-templates/{id}';
};

export type GetV1NameTemplatesByIdResponses = {
    /**
     * OK
     */
    200: HandlersNameTemplateSwagger;
};

export type GetV1NameTemplatesByIdResponse = GetV1NameTemplatesByIdResponses[keyof GetV1NameTemplatesByIdResponses];

export type PutV1NameTemplatesByIdData = {
    /**
     * Update name template
     */
    body: HandlersNameTemplateUpdateRequest;
    path: {
        /**
         * Name Template ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/name-templates/{id}';
};

export type PutV1NameTemplatesByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1NameTemplatesByIdError = PutV1NameTemplatesByIdErrors[keyof PutV1NameTemplatesByIdErrors];

export type PutV1NameTemplatesByIdResponses = {
    /**
     * OK
     */
    200: HandlersNameTemplateSwagger;
};

export type PutV1NameTemplatesByIdResponse = PutV1NameTemplatesByIdResponses[keyof PutV1NameTemplatesByIdResponses];

export type GetV1PoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/policies';
};

export type GetV1PoliciesResponses = {
    /**
     * OK
     */
    200: Array<DbgenPolicy>;
};

export type GetV1PoliciesResponse = GetV1PoliciesResponses[keyof GetV1PoliciesResponses];

export type PostV1PoliciesData = {
    /**
     * Create policy
     */
    body: HandlersPolicyCreateRequest;
    path?: never;
    query?: never;
    url: '/v1/policies';
};

export type PostV1PoliciesErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1PoliciesError = PostV1PoliciesErrors[keyof PostV1PoliciesErrors];

export type PostV1PoliciesResponses = {
    /**
     * Created
     */
    201: DbgenPolicy;
};

export type PostV1PoliciesResponse = PostV1PoliciesResponses[keyof PostV1PoliciesResponses];

export type PostV1PoliciesEvaluateData = {
    /**
     * Download candidate
     */
    body: ModelDownloadCandidate;
    path?: never;
    query?: never;
    url: '/v1/policies/evaluate';
};

export type PostV1PoliciesEvaluateErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1PoliciesEvaluateError = PostV1PoliciesEvaluateErrors[keyof PostV1PoliciesEvaluateErrors];

export type PostV1PoliciesEvaluateResponses = {
    /**
     * OK
     */
    200: ModelEvaluationTrace;
};

export type PostV1PoliciesEvaluateResponse = PostV1PoliciesEvaluateResponses[keyof PostV1PoliciesEvaluateResponses];

export type GetV1PoliciesFieldsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/policies/fields';
};

export type GetV1PoliciesFieldsResponses = {
    /**
     * OK
     */
    200: Array<ModelFieldDefinition>;
};

export type GetV1PoliciesFieldsResponse = GetV1PoliciesFieldsResponses[keyof GetV1PoliciesFieldsResponses];

export type DeleteV1PoliciesByIdData = {
    body?: never;
    path: {
        /**
         * Policy ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/policies/{id}';
};

export type DeleteV1PoliciesByIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1PoliciesByIdResponse = DeleteV1PoliciesByIdResponses[keyof DeleteV1PoliciesByIdResponses];

export type GetV1PoliciesByIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/policies/{id}';
};

export type GetV1PoliciesByIdResponses = {
    /**
     * OK
     */
    200: DbgenPolicy;
};

export type GetV1PoliciesByIdResponse = GetV1PoliciesByIdResponses[keyof GetV1PoliciesByIdResponses];

export type PutV1PoliciesByIdData = {
    /**
     * Update policy
     */
    body: HandlersPolicyUpdateRequest;
    path: {
        /**
         * Policy ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/policies/{id}';
};

export type PutV1PoliciesByIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1PoliciesByIdError = PutV1PoliciesByIdErrors[keyof PutV1PoliciesByIdErrors];

export type PutV1PoliciesByIdResponses = {
    /**
     * OK
     */
    200: DbgenPolicy;
};

export type PutV1PoliciesByIdResponse = PutV1PoliciesByIdResponses[keyof PutV1PoliciesByIdResponses];

export type GetV1PoliciesByIdActionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/policies/{id}/actions';
};

export type GetV1PoliciesByIdActionsResponses = {
    /**
     * OK
     */
    200: Array<DbgenAction>;
};

export type GetV1PoliciesByIdActionsResponse = GetV1PoliciesByIdActionsResponses[keyof GetV1PoliciesByIdActionsResponses];

export type PostV1PoliciesByIdActionsData = {
    /**
     * Create action
     */
    body: HandlersActionCreateRequest;
    path: {
        /**
         * Policy ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/policies/{id}/actions';
};

export type PostV1PoliciesByIdActionsErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1PoliciesByIdActionsError = PostV1PoliciesByIdActionsErrors[keyof PostV1PoliciesByIdActionsErrors];

export type PostV1PoliciesByIdActionsResponses = {
    /**
     * Created
     */
    201: DbgenAction;
};

export type PostV1PoliciesByIdActionsResponse = PostV1PoliciesByIdActionsResponses[keyof PostV1PoliciesByIdActionsResponses];

export type DeleteV1PoliciesByIdActionsByActionIdData = {
    body?: never;
    path: {
        /**
         * Policy ID
         */
        id: string;
        /**
         * Action ID
         */
        actionId: string;
    };
    query?: never;
    url: '/v1/policies/{id}/actions/{actionId}';
};

export type DeleteV1PoliciesByIdActionsByActionIdResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1PoliciesByIdActionsByActionIdResponse = DeleteV1PoliciesByIdActionsByActionIdResponses[keyof DeleteV1PoliciesByIdActionsByActionIdResponses];

export type GetV1PoliciesByIdActionsByActionIdData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/policies/{id}/actions/{actionId}';
};

export type GetV1PoliciesByIdActionsByActionIdResponses = {
    /**
     * OK
     */
    200: DbgenAction;
};

export type GetV1PoliciesByIdActionsByActionIdResponse = GetV1PoliciesByIdActionsByActionIdResponses[keyof GetV1PoliciesByIdActionsByActionIdResponses];

export type PutV1PoliciesByIdActionsByActionIdData = {
    /**
     * Update action
     */
    body: HandlersActionUpdateRequest;
    path: {
        /**
         * Policy ID
         */
        id: string;
        /**
         * Action ID
         */
        actionId: string;
    };
    query?: never;
    url: '/v1/policies/{id}/actions/{actionId}';
};

export type PutV1PoliciesByIdActionsByActionIdErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1PoliciesByIdActionsByActionIdError = PutV1PoliciesByIdActionsByActionIdErrors[keyof PutV1PoliciesByIdActionsByActionIdErrors];

export type PutV1PoliciesByIdActionsByActionIdResponses = {
    /**
     * OK
     */
    200: DbgenAction;
};

export type PutV1PoliciesByIdActionsByActionIdResponse = PutV1PoliciesByIdActionsByActionIdResponses[keyof PutV1PoliciesByIdActionsByActionIdResponses];

export type DeleteV1PoliciesByIdRuleData = {
    body?: never;
    path: {
        /**
         * Policy ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/policies/{id}/rule';
};

export type DeleteV1PoliciesByIdRuleResponses = {
    /**
     * No Content
     */
    204: string;
};

export type DeleteV1PoliciesByIdRuleResponse = DeleteV1PoliciesByIdRuleResponses[keyof DeleteV1PoliciesByIdRuleResponses];

export type GetV1PoliciesByIdRuleData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/policies/{id}/rule';
};

export type GetV1PoliciesByIdRuleResponses = {
    /**
     * OK
     */
    200: DbgenRule;
};

export type GetV1PoliciesByIdRuleResponse = GetV1PoliciesByIdRuleResponses[keyof GetV1PoliciesByIdRuleResponses];

export type PostV1PoliciesByIdRuleData = {
    /**
     * Create rule
     */
    body: HandlersRuleCreateRequest;
    path: {
        /**
         * Policy ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/policies/{id}/rule';
};

export type PostV1PoliciesByIdRuleErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PostV1PoliciesByIdRuleError = PostV1PoliciesByIdRuleErrors[keyof PostV1PoliciesByIdRuleErrors];

export type PostV1PoliciesByIdRuleResponses = {
    /**
     * Created
     */
    201: DbgenRule;
};

export type PostV1PoliciesByIdRuleResponse = PostV1PoliciesByIdRuleResponses[keyof PostV1PoliciesByIdRuleResponses];

export type PutV1PoliciesByIdRuleData = {
    /**
     * Update rule
     */
    body: HandlersRuleUpdateRequest;
    path: {
        /**
         * Policy ID
         */
        id: string;
    };
    query?: never;
    url: '/v1/policies/{id}/rule';
};

export type PutV1PoliciesByIdRuleErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PutV1PoliciesByIdRuleError = PutV1PoliciesByIdRuleErrors[keyof PutV1PoliciesByIdRuleErrors];

export type PutV1PoliciesByIdRuleResponses = {
    /**
     * OK
     */
    200: DbgenRule;
};

export type PutV1PoliciesByIdRuleResponse = PutV1PoliciesByIdRuleResponses[keyof PutV1PoliciesByIdRuleResponses];

export type GetV1SeriesByIdData = {
    body?: never;
    path: {
        /**
         * Series ID
         */
        id: number;
    };
    query?: never;
    url: '/v1/series/{id}';
};

export type GetV1SeriesByIdResponses = {
    /**
     * OK
     */
    200: ModelSeries;
};

export type GetV1SeriesByIdResponse = GetV1SeriesByIdResponses[keyof GetV1SeriesByIdResponses];

export type GetV1SettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/settings';
};

export type GetV1SettingsResponses = {
    /**
     * OK
     */
    200: HandlersSettingsListResponse;
};

export type GetV1SettingsResponse = GetV1SettingsResponses[keyof GetV1SettingsResponses];

export type PatchV1SettingsData = {
    /**
     * Patch request
     */
    body: HandlersPatchRequest;
    path?: never;
    query?: never;
    url: '/v1/settings';
};

export type PatchV1SettingsErrors = {
    /**
     * Bad Request
     */
    400: {
        [key: string]: string;
    };
};

export type PatchV1SettingsError = PatchV1SettingsErrors[keyof PatchV1SettingsErrors];

export type PatchV1SettingsResponses = {
    /**
     * No Content
     */
    204: string;
};

export type PatchV1SettingsResponse = PatchV1SettingsResponses[keyof PatchV1SettingsResponses];
